### ISSUE TITLE
Upgrade Minio Version in the SCB Operator chart.

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#1012]
### Is your feature request related to a problem?

The Minio Chart which is referenced in the Operator seems to be outdated and needs an upgrade to the latest release: https://artifacthub.io/packages/helm/securecodebox/operator?modal=security-report 

### Describe the solution you'd like

Upgrade the Minio dependency (https://helm.min.io/) to the latest version: https://github.com/secureCodeBox/secureCodeBox/blob/main/operator/Chart.yaml

**Comment by J12934** [comment]
@rseedorff this seems to be a duplicate of #755

**Comment by rseedorff** [comment]
👀 thats right! My fault 🤦‍♂️
