### ISSUE TITLE
Update release-drafter template to implement ADR-0011

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1023]
We have to update the release-drafter template to include a new section for breaking changes that is prominently shown and highlighted at the very top of the release notes. This is done to implement [ADR-0011](https://github.com/secureCodeBox/secureCodeBox/pull/936).

**Comment by SebieF** [comment]
Isn't this already done? [release-darfter.yml](https://github.com/secureCodeBox/secureCodeBox/blob/ab386f8ba3950e7a6093fcb27e6f944f8bdcae4d/.github/release-drafter.yml#L8)
