### ISSUE TITLE
Build Docker Images for ARM Processors

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#1026]
## ➹ New Feature implementation request

We currently only build our docker images for x86 Intel / AMD Architectures.
These images can't run nativly on ARM Devices, e.g. RaspberryPi, AWS ARM Machines and require additional virtualization to run on the new M1 ARM based Macs.

### Describe the solution you'd like

Prebuild (at least our most important images, `operator`, `lurker`, `parser-sdk`, `hook-sdk`, `auto-discovery-kubernetes`)

### Describe alternatives you've considered

Have users build them by themself / use runtime hardware emulation to run our x86 images.

### Additional context

Our build infrastructure already supports building images for multiple architecture (https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#platform).

Some of our golang images (operator & lurker at least) have the plattform / archtiecture hardcoded in the docker file, these would have to be removed / changed.

**Comment by Weltraumschaf** [comment]
I work ATM on organizing an M1 machine.
