### ISSUE TITLE
Install.sh tries to install non-existent version of operator

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1030]
### Describe the bug
Running `install.sh` (from the `bin` folder) tries to install the operator in the version `docker.io/securecodebox/operator:v3.1.0-alpha1`, which does not exist.

### Steps To Reproduce
1. Start with a fresh cluster
2. Run `install.sh`, install nothing but the operator
3. Observe that the installed operator fails to come up:
```bash
% k get pods -n securecodebox-system                             
NAME                                                READY   STATUS             RESTARTS   AGE
securecodebox-controller-manager-6dd5c84787-mxf6b   0/1     ImagePullBackOff   0          3m14s
securecodebox-operator-minio-cddbb8f9f-4f4v9        1/1     Running            0          7m50s

% k describe -n securecodebox-system pod securecodebox-controller-manager-6dd5c84787-mxf6b 
[... snip ...]
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m55s                  default-scheduler  Successfully assigned securecodebox-system/securecodebox-controller-manager-6dd5c84787-mxf6b to minikube
  Normal   Pulling    3m24s (x4 over 4m51s)  kubelet            Pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"
  Warning  Failed     3m23s (x4 over 4m48s)  kubelet            Failed to pull image "docker.io/securecodebox/operator:v3.1.0-alpha1": rpc error: code = Unknown desc = Error response from daemon: manifest for securecodebox/operator:v3.1.0-alpha1 not found: manifest unknown: manifest unknown
  Warning  Failed     3m23s (x4 over 4m48s)  kubelet            Error: ErrImagePull
  Warning  Failed     2m56s (x6 over 4m48s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m42s (x7 over 4m48s)  kubelet            Back-off pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"
```

### Expected behavior
It should either install the latest version of the operator, or build and deploy the operator from source if that is the intended behavior.

### System (please complete the following information):
Latest SCB on MacOS with minikube as Kubernetes runtime.

**Comment by avicoder** [comment]
@J12934 - How did it was resolved at the end? Slack thread is not longer accessible.

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m52s                   default-scheduler  Successfully assigned securecodebox-system/securecodebox-controller-manager-d757f7656-zrlcq to docker-desktop
  Normal   Pulling    7m8s (x4 over 8m51s)    kubelet            Pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"
  Warning  Failed     7m4s (x4 over 8m48s)    kubelet            Failed to pull image "docker.io/securecodebox/operator:v3.1.0-alpha1": Error response from daemon: manifest for securecodebox/operator:v3.1.0-alpha1 not found: manifest unknown: manifest unknown
  Warning  Failed     7m4s (x4 over 8m48s)    kubelet            Error: ErrImagePull
  Warning  Failed     6m54s (x6 over 8m47s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m43s (x19 over 8m47s)  kubelet            Back-off pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"

```

**Comment by Ilyesbdlala** [comment]
> @J12934 - How did it was resolved at the end? Slack thread is not longer accessible.
> 
> ```
> Events:
>   Type     Reason     Age                     From               Message
>   ----     ------     ----                    ----               -------
>   Normal   Scheduled  8m52s                   default-scheduler  Successfully assigned securecodebox-system/securecodebox-controller-manager-d757f7656-zrlcq to docker-desktop
>   Normal   Pulling    7m8s (x4 over 8m51s)    kubelet            Pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"
>   Warning  Failed     7m4s (x4 over 8m48s)    kubelet            Failed to pull image "docker.io/securecodebox/operator:v3.1.0-alpha1": Error response from daemon: manifest for securecodebox/operator:v3.1.0-alpha1 not found: manifest unknown: manifest unknown
>   Warning  Failed     7m4s (x4 over 8m48s)    kubelet            Error: ErrImagePull
>   Warning  Failed     6m54s (x6 over 8m47s)   kubelet            Error: ImagePullBackOff
>   Normal   BackOff    3m43s (x19 over 8m47s)  kubelet            Back-off pulling image "docker.io/securecodebox/operator:v3.1.0-alpha1"
> ```

We set install.sh to get the helm charts from the remote helm chart museum, instead of directly from source https://github.com/secureCodeBox/secureCodeBox/pull/1282/ . So the process is the same as our regular installation instructions :https://www.securecodebox.io/docs/getting-started/installation
The latest version is pulled, right now it's 4.3.0.  `v3.1.0-alpha1` is our placeholder version in src code.
Make sure your  install.sh is up-to-date, and try running `helm repo update` before deploying the secureCodeBox operator.
If the problem persists, please let us know, by describing your setup and how to reproduce the error :)
