### ISSUE TITLE
Engine exited and unhealthy containers

### ISSUE THREAD

**Issue by Equ1n0x** [secureCodeBox/secureCodeBox#109]
**Describe the bug**
Containers are unhealthy after I've ran docker-compose. Enige container exited.

**To Reproduce**
1. git clone https://github.com/secureCodeBox/secureCodeBox
2. cd secureCodeBox
3. docker-compose -f docker-compose.yml up

**Expected behavior**
Containers go up and are functional. SecureCodeBox works like a charm ;-)

**System (please complete the following information):**
 - OS: macOS Mojava
 - Docker version 19.03.5, build 633a0ea
 - docker-compose version 1.25.2, build 698e2846
 - Not applicable

**Screenshots / Logs**
For engine logs: https://pastebin.com/CiYYU34c

**Comment by rseedorff** [comment]
Hi @Equ1n0x ,
thanks for reporting this issue with log files!

It seems to me there is a little race condition bug in our docker-compose file. I fixed it with an additional healthcheck to ensure the mysql db is ready before the engine starts. 

Can you please check if this solves your issue? (by using the linked branch)

**Comment by rseedorff** [comment]
Hi @Equ1n0x , i added a new vagrant file to create a consistent virtual box image for local testing. Maybe this helps in your case to start the secureCodeBox stack, based on vagrant.

Can you please check if this solves your issue?

**Comment by jhulick** [comment]
The Vagrant setup fixed this issue for me.
