### ISSUE TITLE
secureCodeBox containers fails to start on Windows Node.

### ISSUE THREAD

**Issue by sourabhsdeshpande** [secureCodeBox/secureCodeBox#1092]
### Describe the bug
In Kubernetes cluster where we have Windows & Linux nodes, if we install SCB/operator then containers gives warnings as shown in screenshot. Container remains in 'Pending' state forever. This happens only when Windows node is picked up for running the containers.

### Steps To Reproduce
1. Setup Kubernetes cluster where there are some Windows & Linux nodes. 
2. Install SecureCodebox/Operator.
3. It gives warnings as shown below for different containers.
   **Failed to pull the image "docker.io/securecodebox/operator:3.6.0": rpc error: code = Unknown desc = image operating system "linux" cannot be used on this platform**

### Expected behavior
Provide support for to specify **nodeSelector** so that users can specify to use **Linux** node.

### System (please complete the following information):
 - secureCodeBox Version/Release: 3.8.0
 - OS: Linux
 - Kubernetes Version: v1.21.3(Client), v1.21.2(Server)
 - Docker Version: 20.10.13
 - Browser: Not applicable

### Screenshots / Logs

![SCB Installation error For Windows node](https://user-images.githubusercontent.com/101176914/161803764-c60a1639-6b6c-42b4-b40e-a1fd0d70f152.png)

**Comment by J12934** [comment]
Yeah at the moment none of our containers, and as far as I know, any scanner we integrate with supports windows nodes.

Totally agree that we should mark them with the appropriate label selectors to ensure that SCB still works on clusters with some windows node in them.

For the moment it would probably be best too add them to both the operator as well as any job we start, as none of them are supported on windows.

**Comment by sourabhsdeshpande** [comment]
Thank you for the reply.
 Yes!
Providing nodeSelector support as quick fix for the moment would make sure that SCB works fine with the Linux nodes **always**(even in case of mixed nodes in cluster)

**Comment by Weltraumschaf** [comment]
Todo: Add node selectors to all Helm templates that they require Linux.
