### ISSUE TITLE
Add the scanner Astra

### ISSUE THREAD

**Issue by wurstbrot** [secureCodeBox/secureCodeBox#111]
To test for common API vulnerabilities like rate limiting, the scanner Astra (https://github.com/flipkart-incubator/Astra) looks promissing.

**Comment by wurstbrot** [comment]
In the code, I see it is based on loginrate limiting, https://github.com/flipkart-incubator/Astra/blob/master/modules/rate_limit.py :(

**Comment by rseedorff** [comment]
Hi @wurstbrot 
We already added Astra to our backlog: #76 ;-)
