### ISSUE TITLE
CI runs twice on internal pull requests

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1128]
## 🐞 Bug report
The changes made in #1123 seem to lead to the CI running twice on internal pull requests (e.g. those created by the dependency bot):
![grafik](https://user-images.githubusercontent.com/1688580/164438146-68d946e9-4d9d-4128-a22e-c8ce57290e04.png)

See #1127 for an example.

cc @Ilyesbdlala

**Comment by Ilyesbdlala** [comment]
Quoting #1123 
> This will trigger the CI BOTH on pushes and pull requests opened.
> That means that duplicate workflows will happen when a new PR is opened:
> Example:
> https://github.com/secureCodeBox/secureCodeBox/actions/runs/2194291551
> https://github.com/secureCodeBox/secureCodeBox/actions/runs/2194471682
> 
> But it will allow for the CI to work on Forks
> Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-multiple-events
> 
> Possible solution: https://github.com/marketplace/actions/skip-duplicate-actions.

AFAIK there isn't an elegant way of saying that GitHub actions should either run on  _push_ trigger OR _pull_request_ trigger.  
The workflows will only be duplicated at the time of opening the PR.
This is for now a compromise to allow the CI to work on Forks PRs.

**Comment by malexmave** [comment]
Ah, sorry, I didn't read the PR, it seems.

Should we leave this open as a placeholder for "maybe we want to do something about this at some point, and implement the skip-duplicate-actions solution", or do you think we should just accept that this is the case and move on?

**Comment by Ilyesbdlala** [comment]
> Ah, sorry, I didn't read the PR, it seems.
> 
> Should we leave this open as a placeholder for "maybe we want to do something about this at some point, and implement the skip-duplicate-actions solution", or do you think we should just accept that this is the case and move on?

I would leave it as a placeholder for this issue. Since it's probably possible to resolve this through 3rd party GitHub actions such as: https://github.com/marketplace/actions/skip-duplicate-actions

**Comment by Ilyesbdlala** [comment]
Resolved in https://github.com/secureCodeBox/secureCodeBox/pull/1213
