### ISSUE TITLE
How to add a suffix to output files

### ISSUE THREAD

**Issue by Spritekin** [secureCodeBox/secureCodeBox#1137]
## Your Question

I got two scheduled scans to two different sites which appear in the cluster as:
```
NAME                        TYPE            INTERVAL   FINDINGS
zap-scan-earnd-admin        zap-full-scan   168h       19
zap-scan-egw-adminconsole   zap-full-scan   168h       21
```

The scans generate pods like these ones.
```
scan-zap-scan-earnd-admin-1650962558-p77qz-dhn6x
scan-zap-scan-egw-adminconsole-1650962558-82c24-m6zks 
```

However, when the scan results are written to the S3 bucket, we get folders like:
```
scan-202639fa-0083-42b0-a401-91b167c44370/
scan-da96b881-9b2f-4b9c-93da-afe3d315ce5c/
```

There is no way to identify which one is the result of a particular scan or even from a particular run.

What I would like to see is the folders in S3 like this:
```
zap-scan-earnd-admin-2022-04-03-12-35/
zap-scan-earnd-admin-2022-04-10-12-35/
zap-scan-egw-adminconsole-2022-04-03-12-35/
zap-scan-egw-adminconsole-2022-04-10-12-35/
```

That is, I would like to see the folder named relative to the scan name and the date/time when it was run.

Is there a way to do this?

Thanks for your help.

**Comment by J12934** [comment]
Hi 👋
again thanks for the feedback, it always very helpful to hear where the pain points are 🙏 

Short answer: No, it currently not possible to change the naming scheme for the result files in the S3 bucket.

The names are deterministic though, they are based on the scans uuid, not the name.
You can list the scans uuid together with the name by running `kubectl get scans -o wide`
You can also get full urls to directly download the results from by taking a look at the scans status.

We've choosen the uuid for the file name in s3 as they are (nearly) guaranteed to be unique, as to avoid problems where a cleanup of previous results have failed and old results would still be present under the same name. (As the scan name can be repeated for non ScheduledScans, also for scans in separate namespaces). This is a edge case scenario, but one we'd rather not have enabled by default.

It would be possible thought to have this be configurable by allowing the users to pass in a golang template string which could then be used to generate the S3 path. The default would then be something like

```golang
scan-{{ .Scan.Metadata.UID }}/{{ .Filename }}
```

and to achieve the structure you've proposed you could pass in something the follwing template:

```golang
{{ .Scan.Metadata.Name }}/{{ .Filename }}
```

I'll convert this into a enhancment ticket, as this is somethign which we could add as a feature.
