### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by catalinvr** [secureCodeBox/secureCodeBox#114]
**Is your feature request related to a problem? Please describe.**
Guys, I saw that some branches are merged in master but no tags are applied.
This is not good for a production environment. I would like to know exactly what revision I've cloned and later to check all changes when i will plan an upgrade.

**Describe the solution you'd like**
After each merge in master a new git tag needs to be applied

**Describe alternatives you've considered**
NO

**Additional context**

**Comment by J12934** [comment]
Hi 👋
We push out releases in our separate services on a pretty regular basis. E.g. see the releases of the engine (https://github.com/secureCodeBox/engine/releases)
This repo is more of a collection of various documentations and examples, and doesn't benefit too much from point in time versions.

**Comment by rseedorff** [comment]
Hi @catalinvr 
thanks for your heads up! As @J12934 already mentioned we try to keep all services stable based on regular release tags. Do you use this release tags in your environment? Which merge branches do you mean exactly? If we missed something it would be helpful to get some more details about your setup :)

**Comment by catalinvr** [comment]
Hi @rseedorff 

I'm using the repo to spin up the app. Once I will pin the master branch on my automation tool (chef), it will pull all new changes from this branch (every time when starts the cron). In case that I will set a tag on my automation script, I will prevent any changes.

But that depends on the purpose of this repo. For me was exactly what I need to spin up the app with all components. 

Thank you,
Catalin

**Comment by J12934** [comment]
This is now fixed with out new secureCodeBox version 2.
The components all use fixed image versions and we regularly release new version from master
