### ISSUE TITLE
vagrant install broken 

### ISSUE THREAD

**Issue by wurstbrot** [secureCodeBox/secureCodeBox#1140]
I am unsing the vagrant setup with libvirt provider and follow the docs https://docs.securecodebox.io/docs/getting-started/first-scans until `kubectl get scans`.  The documentated state of a scan job is not comming:
```
$ kubectl get scans
NAME                                          TYPE                STATE   FINDINGS
nmap-scanme.nmap.org                          nmap
zap-authenticated-full-scan-juiceshop-basic   zap-advanced-scan
```
Am I supposed to do more than vagrant up and the steps in that documentation? Maybe the operator is not installed?

**Comment by Weltraumschaf** [comment]
Hi @wurstbrot thanks for submission.

A `vagrant up` should be sufficient. I take a look.
