### ISSUE TITLE
Got "panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory" when develop new scan type

### ISSUE THREAD

**Issue by RealAlphaMan** [secureCodeBox/secureCodeBox#1147]
I'm creating new scan type grype for secureCodeBox system.
I work with Digital Ocean, not minikube

When I get logs of pods, there's 2 containers in pod: grype and lurker. The grype container works normally, but the lurker got error: 
```
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

goroutine 1 [running]:
main.waitForMainContainerToEnd({0x7ffc7605bc30, 0x5}, {0xc000040009, 0x26}, {0xc00004200a, 0x7})
	/workspace/main.go:110 +0x117
main.main()
	/workspace/main.go:57 +0x465

```

## Describe pods:
```
  lurker:
    Container ID:  containerd://c74f44c87294c283df9c045c653b2c02a408752ac805173abbe0417c75629341
    Image:         docker.io/securecodebox/lurker:3.9.1
    Image ID:      docker.io/securecodebox/lurker@sha256:db9d4c5d5fe00cdc0a3a4cf270352492ec7c125018a2b6a77d271ef37f996191
    Port:          <none>
    Host Port:     <none>
    Args:
      --container
      grype
      --file
      /home/securecodebox/grype-results.json
      --url
      http://securecodebox-operator-minio.securecodebox-system.svc.cluster.local:9000/securecodebox/scan-39ec61cb-e605-4e2c-bb80-a345e5682b58/grype-results.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YOURACCESSKEY%2F20220502%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220502T120406Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=665d24dc16118e6545de452004734e82fba270e7eae391e25c76b0e5f1243be6
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 02 May 2022 19:04:40 +0700
      Finished:     Mon, 02 May 2022 19:04:40 +0700
    Ready:          False

```

Source code: https://github.com/RealAlphaMan/grype-scantype-scb

How can I fix it? Thank you!

**Comment by J12934** [comment]
Hi again 👋

I'm guessing the problem will be the `automountServiceAccountToken` being set to false in you scan job template: https://github.com/RealAlphaMan/grype-scantype-scb/blob/master/templates/grype-scan-type.yaml#L25

The lurker needs the service account token to talk to the Kubernetes API. It uses it to check the primary container of the pod (the scan container) is completed.

**Comment by J12934** [comment]
@RealAlphaMan think the problem here is now that the result is not acutally written into the file you configured in the scanType (`/home/securecodebox/grype-results.json`), when I see it correctly you can configure which file gets written to using the `--file` command in grype. We usually do this right in the `command` section of the scanType.

**Comment by RealAlphaMan** [comment]
@J12934 Thank you again! I've fixed all error and run correctly
