### ISSUE TITLE
:wrench:  Maintenance: Revisit nuclei integration tests

### ISSUE THREAD

**Issue by SebieF** [secureCodeBox/secureCodeBox#1162]
There are currently two nuclei integration tests. 

- [x] One tests against bodgeit demo target, but is currently disabled (commented out). Unfortunately I could not find a reason why it was disabled in the git history. Maybe it should be turned on again?

- [ ] The second one tests against http://securecodebox.io. However, [it is not named correctly](https://github.com/secureCodeBox/secureCodeBox/blob/3dbbaf26d674082ec147ba987fc536900a3f29f9/scanners/nuclei/integration-tests/nuclei.test.js#L30). Maybe we should also re-evaluate if we actually want to run tests against our own website (might be slow and expensive).

**Comment by Weltraumschaf** [comment]
Decision backlog grooming: We delete the second test against securecodebox.io.
