### ISSUE TITLE
Add a PersistenceProvider for ThreadFix

### ISSUE THREAD

**Issue by JavanXD** [secureCodeBox/secureCodeBox#120]
It would be nice if as an alternative to Defect Dojo, ThreadFix could also be included as StorageProvider.

ThreadFix has a public API: https://denimgroup.atlassian.net/wiki/spaces/TDOC/pages/22842096/ThreadFix%2BAPI 

Unfortunately it is a commercial tool in contrast to DefectDojo, but it can also be found in many corporate environments.

**Comment by rseedorff** [comment]
Thx for your suggestion! Maybe someone from our community can help us here? Feedback about this feature request would be nice :)

**Comment by Weltraumschaf** [comment]
We do not plan to integrate this at the moment. If there is more need from the community for this scanner please leave a comment here.
