### ISSUE TITLE
Error when installing operator & CRD's

### ISSUE THREAD

**Issue by masterminerking** [secureCodeBox/secureCodeBox#1216]
Hi

I am trying to install securecodebox for the first time but when I follow the instructions below I continually get an error:

# Add the secureCodeBox Helm Repo
helm repo add secureCodeBox https://charts.securecodebox.io

# Create a new namespace for the secureCodeBox Operator
kubectl create namespace securecodebox-system

# Install the Operator & CRD's
helm --namespace securecodebox-system upgrade --install securecodebox-operator secureCodeBox/operator

https://docs.securecodebox.io/docs/getting-started/installation/

The error that I get is shown below and this occurs when I run the command to install the Operator & CRD's:

Release "securecodebox-operator" does not exist. Installing it now.
Error: apiVersion 'v2' is not valid. The value must be "v1"

Thanks

**Comment by J12934** [comment]
Hi @masterminerking 👋

Can you post your version of helm and kubernetes that you have?

E.g. from the cli:

```bash
helm version
kubectl version
```

**Comment by masterminerking** [comment]
I have also just tried this with a new kubernetes cluster and helm version v2.17.0 and kubernetes version 1.23.5 and I still get the same error

**Comment by J12934** [comment]
can you please recheck that you run the initial installation with helm 3?

The error message is the typical "helm 2 tries to install a helm 3+ chart" error message

**Comment by J12934** [comment]
Awesome, closing this issue now. 👍
Feel free to reach out via another issue or slack if you run into any other problems
