### ISSUE TITLE
New Scanner: HTTPLoot

### ISSUE THREAD

**Issue by twwd** [secureCodeBox/secureCodeBox#1247]
## 🚓  New Scanner implementation request

[HTTPLoot](https://github.com/redhuntlabs/HTTPLoot) is a new

> automated tool which can simultaneously crawl, fill forms, trigger error/debug pages and "loot" secrets out of the client-facing code of sites.

This seems like a good fit to the scb.

## Steps to implement a new scanner
Hint: A general guide how to implement a new SCB scanner is documented [here](https://www.securecodebox.io/docs/contributing/integrating-a-scanner)

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox/tree/master/scanners)
- [ ] Add a `README.gotmpl` and give a [brief overview](https://www.securecodebox.io/docs/contributing/integrating-a-scanner/readme) of the scanner and its configuration options.
- [ ] Add a HelmChart and document all configuration options.
- [ ] Implement a new scanner specific `scan-type.yaml`
- [ ] Implement a new scanner specific `parse-definition.yaml`
- [ ] Add (optional) some `cascading-rules.yaml` like documented [here](https://www.securecodebox.io/docs/api/crds/cascading-rule)
- [ ] Add (optional) a `Dockerfile` for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage
- [ ] Add some example `scan.yaml` and `finding.yaml` files in the [example folder](https://www.securecodebox.io/docs/contributing/integrating-a-scanner/examples-dir)
- [ ] Implement a [new integration or E2E test](https://www.securecodebox.io/docs/contributing/integrating-a-scanner/integration-tests) for the hook [here](https://github.com/secureCodeBox/secureCodeBox/tree/master/tests/integration)

**Comment by Weltraumschaf** [comment]
Scanner seems to be not maintained anymore.
