### ISSUE TITLE
Zap-advanced scan: Ajax spider puts random text in the form fields even when 'randomInputs' is set to false

### ISSUE THREAD

**Issue by sourabhsdeshpande** [secureCodeBox/secureCodeBox#1265]
### Describe the bug
Even when a value for **randomInputs** is set to **false**, spider still puts in random text in the form fields and then finds the urls.
When form field is drop down, it selects first item from the list and so on...

### Steps To Reproduce

1. Create a yaml file to scan application using Zap-advanced-scan.
2. Make sure that, Spider is ajax spider (ajax: true) and **randomInputs** is set to **false**.
3. Run the scan. If you see the logs, it shows that spider has put text in the input form fields.

### Expected behavior
Spidering **should not** put any text in any form field when **randomInputs** is set to **false**.

### System:

 - secureCodeBox Version/Release: 3.10.0
 - OS: Linux
 - Kubernetes Version: Client v1.21.3, Server v1.22.6
 - Docker Version: 20.10.13
 - Browser: Not applicable

### Screenshots / Logs
![image](https://user-images.githubusercontent.com/101176914/178274823-92019782-640c-427c-8f28-8643cce64f24.png)

**Comment by sourabhsdeshpande** [comment]
Hi @rseedorff,
Thanks for the quick reply. :)

I saw a log in the zap-sidecar container for the randomInputs with below text. 

_[ZAP-ProxyThread-69] DEBUG org.zaproxy.zap.extension.api.API - handleApiRequest http://zap/JSON/ajaxSpider/action/setOptionRandomInputs/?Boolean=False&apikey=_

Zap automation API is called for this option. 
Hence thought it might be a bug.

**Comment by rseedorff** [comment]
Oh ok, you are right, thats my fault 🤔. You are right, the config option is implemented:

https://github.com/secureCodeBox/secureCodeBox/blob/dae41cde8547c014d72b74070cae065707b237cb/scanners/zap-advanced/scanner/zapclient/spider/zap_spider_ajax.py#L156-L160

On the first look there seems to be a type miss match 🙈

`if self._is_not_empty_integer("randomInputs", spider_config): ` must be 
`if self._is_not_empty_bool("randomInputs", spider_config): `

**Comment by sourabhsdeshpande** [comment]
Hi @rseedorff 

I also had the same suspicion on that code however, if you see the log entry below, it **does send the correct api request**... May be faulty code doesn't matter in this case since value we are passing is **false**.

[ZAP-ProxyThread-69] DEBUG org.zaproxy.zap.extension.api.API - handleApiRequest http://zap/JSON/ajaxSpider/action/**setOptionRandomInputs/?Boolean=False**&apikey=

I also checked some other logs for boolean type of fields and request looks similar.
Maybe something more is missing/incorrect?

**Comment by rseedorff** [comment]
Good point, maybe it's also a problem related directly to Zap or the ZAP API 🤔

Have you tried to test your configuration manually in the Zap App? In our experience it's often helpful to first try the configuration options one would like to automate with the zap-advanced scanType to validate them. I haven't used this config option yet and will also try to look into that more deeply 👀

**Comment by sourabhsdeshpande** [comment]
Yeah...
I have tried from the Zap application UI directly with non-headless mode and there I could see that it works...
Just now I have also tested using Zap API, settings set via API call are reflected in the tool UI... So it seems it is working too...

**Comment by the-simmon** [comment]
@sourabhsdeshpande can you post the logs were you see that the ajax spider inputs random stuff? I cant seem to find it. Thanks :)

**Comment by Weltraumschaf** [comment]
We deprecate ZAP Advanced and ZAP Baseline: https://github.com/secureCodeBox/secureCodeBox/issues/1851
