### ISSUE TITLE
How to get started with defectdojo for security orchestration

### ISSUE THREAD

**Issue by lucifer140** [secureCodeBox/secureCodeBox#1279]
......HELP.......
i want to get started with defectdojo but cannot start ...i didnt know where to start from...
i have installed it with docker-compose and helmchart...the dashboard is up..but confused about how to start and integrate with other tools...
plz anyone guide me to integrate with other tools for checking securityy...

**Comment by Ilyesbdlala** [comment]
Hi, we appreciate your interest in using secureCodeBox for ensuring security in your applications. 
For a better understanding of SCB I would recommend checking out our How-Tos available [here](https://www.securecodebox.io/docs/how-tos).
Information on how to implement different scanners is found [here](https://www.securecodebox.io/docs/scanners) and how to use them in conjuncture with DefectDojo is found [here](https://www.securecodebox.io/docs/hooks/defectdojo).
I hope that's a good starting point. Please use our [Slack channel ](https://join.slack.com/t/securecodebox/shared_invite/enQtNDU3MTUyOTM0NTMwLTBjOWRjNjVkNGEyMjQ0ZGMyNDdlYTQxYWQ4MzNiNGY3MDMxNThkZjJmMzY2NDRhMTk3ZWM3OWFkYmY1YzUxNTU%22)for further questions.

**Comment by SebieF** [comment]
We created a tutorial for your exact problem lately, please refer to it and let us know if you still experience problems: https://www.securecodebox.io/docs/how-tos/persistence-storage
