### ISSUE TITLE
Defect Dojo hook pods killed with OOMS  message. No report uploaded in defect dojo

### ISSUE THREAD

**Issue by rahulkiit** [secureCodeBox/secureCodeBox#1305]
Defect Dojo hook pods killed with OOMS  message. No report uploaded in defect dojo

- Deploy defectdojo hook and run the nmap scan.
- All steps executed correctly and only pods created for defect dojo killed with message OOMSkilled.
- There is no option to increase the resource limit for defectdojo hook.
https://github.com/secureCodeBox/secureCodeBox/blob/main/hooks/persistence-defectdojo/values.yaml

I also tried building custom docker image doe defectdojo to restrict memory for Java process in docker image but that also didn't help.

If there is option to increase resource limit for defectdojo hook then it will be great.

Screen Print : 
![image](https://user-images.githubusercontent.com/9696033/184623244-bd3403a0-e1fd-4d5f-a191-3a0e1f892365.png)

**Comment by J12934** [comment]
Hi @rahulkiit,
thats definitely a bug. Unfortunatly not a easy one to fix as the memory limits for hooks are currently fixed and can't be adjusted on a per hook basis. Changing this would require a change to the ScanCompletionHook CRD to support this.

I'm wondering how this is happening only here. We've used the hooks before to upload sometimes quite massive reports to DefectDojo and haven't had problems so far. Did you have particularly many findings in the report or is the container runtime OOMKiller just more aggressive then on most other clusters?

**Comment by rahulkiit** [comment]
I am using Nmap scan default example. Only 5 findings reported that example. I saw that Elastic search hook got resource value attribute to update the resource limit. If same option can be enabled via helm chart to override the resources limit then this can be addressed.

**Comment by rahulkiit** [comment]
I think this issue is already patched in v 3.15.x . this can be closed.

**Comment by rsmartins78** [comment]
Still facing the same error at 3.15.2

**Comment by J12934** [comment]
Hi @rsmartins78, thank you for the update / reminder :)

The default limits have not been changed (yet) so it can still fail (depending on a couple of factors)

You can change the resource requirements for the DefectDojo hook now though to increase the limit and avoid OOM kills.

You can increase them using the [helm values](https://github.com/secureCodeBox/secureCodeBox/blob/main/hooks/persistence-defectdojo/values.yaml#L39). E.g. to increase the memory limit of the hook:

```bash
helm upgrade --install persistence-defectdojo secureCodeBox/persistence-defectdojo --set="hook.resources.limits.memory=512Mi"
```

Can you confirm that this resolves the issue on your end? If so we could increase the current default. 
I could not get this reproduced so far.

The example you've posted looks interesting. The args are NOT duplicated, they only look so the first set are presigned urls from S3 to download the findings / raw result, the second set is to upload / overwrite them if the have changed (needed for the `syncFindingsBack` mode).

The environment variables are indeed duplicated, this might be either a bug in the operator or the hooks helm chart (which looks ok on first glance). Have you seen this issue happen with other hooks too?

**Comment by rahulkiit** [comment]
I used following values in values.yaml to fix the resource issue with Defectdojo hook. I intentionally used larger values so that I don't have to face the resource issue. I didn't wanted to spend time on trial an error to find exact resource uses.

resources: { requests: { cpu: "200m", memory: "700Mi" }, limits: { cpu: "400m", memory: "900Mi" } }

**Comment by Ilyesbdlala** [comment]
We will be changing change the default `resources` values to accommodate more users. @rsmartins78 @rahulkiit Do these values work for you ? I am also unable to reproduce the problem with the default resources values. 
```yaml
  resources: { 
    requests: { 
      cpu: "200m",
      memory: "256Mi"
    },
    limits: { 
      cpu: "400m",
      memory: "512Mi"
    }
  }
```

**Comment by rahulkiit** [comment]
I was able to avoid this issue by overriding the default resource limit to higher value. Any default value that will be set might be low or high depending on what that POD is doing. I think as long as overriding the default value available it's fine to keep any default value
