### ISSUE TITLE
Information trigger for failed ZAP-Advanced nightly builds

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#1331]
Currently the maintainer team has issue getting informed in the case the ZAP-Advanced nightly scheduled integration test fails 🤔 

Therefore we would like to get a more active push notification for example as slack channel notification within the secureCodeBox slack Team.

**Comment by the-simmon** [comment]
This ticket is in `to review` but i cant find a linked PR?
