### ISSUE TITLE
Support paths with spaces in Makefile

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1353]
## 🐞 Bug report
The Makefile does not support paths with spaces.

### Describe the bug
If the repository is cloned to a location where the path leading to the repository contains spaces, Makefile commands can fail.

Try the following:
```bash
$ cd /tmp
$ git clone https://github.com/securecodebox/secureCodeBox "secure Code Box"
$ cd "secure Code Box"
$ make create-new-scanner NAME=test
find: /tmp/secure: No such file or directory
find: Code: No such file or directory
find: Box: No such file or directory
rm -rf /tmp/secure Code Box/scanners/test
cp -r /tmp/secure Code Box/.templates/new-scanner/ /tmp/secure Code Box/scanners/test
cp: Box/scanners/test is not a directory
```

### Expected behavior
The Makefile should create a new scanner, instead of choking on the space and dying (or, even worse, copying stuff around randomly based on prefixes and polluting the file system of the user, or deleting their files, or...).

### System (please complete the following information):
Should apply equally to Mac OS (tested), Linux (untested), Windows with WSL (tested)

### Ideology
Yes, I know, spaces in folder names are considered an antipattern by some people. Still, in many situations (e.g., if you are using Windows with WSL and use your full name as username, and you drop your stuff in the "My Files" area of the system), you are pretty much guaranteed to encounter spaces. Instead of forcing developers to switch their workflows and where they store their code, we should just support this use case, if at all possible. And if we do not want to support this for whatever reason, we should ensure that the Makefile checks if there are spaces in the folder path, and refuse to perform operations that may break because of them, instead of bugging out and doing weird stuff that may or may not end up creating and deleting files in random places.

**Comment by malexmave** [comment]
This seems to be a problem caused by the fix to https://github.com/secureCodeBox/secureCodeBox/issues/754 in commit https://github.com/secureCodeBox/secureCodeBox/commit/eceb12599cffaaf9dbb380cc4ac105f4541ad26f, where all quotes were removed from the Makefile. This breaks support for spaces in the paths, and it also breaks [the `sed` call in the `find -exec` part of the Makefile](https://github.com/secureCodeBox/secureCodeBox/blob/main/Makefile#L76-L78), which will now return:

```
make create-new-scanner NAME=ffuf
rm -rf /tmp/secureCOdeBox/scanners/ffuf
cp -r /tmp/secureCOdeBox/.templates/new-scanner/ /tmp/secureCOdeBox/scanners/ffuf
find /tmp/secureCOdeBox/scanners/ffuf -type f ! -name tmp \
		-exec sed -n s/new-scanner/ffuf/g;w /tmp/secureCOdeBox/scanners/ffuf/tmp {} \; \
		-exec mv /tmp/secureCOdeBox/scanners/ffuf/tmp {} \;
find: -exec: no terminating ";" or "+"
11:13  up  3:23, 2 users, load averages: 2,10 2,20 2,11
USER     TTY      FROM              LOGIN@  IDLE WHAT
mv /tmp/secureCOdeBox/scanners/ffuf/templates/new-scanner-parse-definition.yaml \
		/tmp/secureCOdeBox/scanners/ffuf/templates/ffuf-parse-definition.yaml
mv /tmp/secureCOdeBox/scanners/ffuf/templates/new-scanner-scan-type.yaml \
		/tmp/secureCOdeBox/scanners/ffuf/templates/ffuf-scan-type.yaml
```

I think we need some test cases for our Makefiles...

**Comment by Weltraumschaf** [comment]
The important part missed by me is:

> So, if the shell expects and can interpret a quoted string, then you should use quotes. Where the shell doesn't expect or won't correctly interpret a quoted string, you should not use quotes. ([SO](https://stackoverflow.com/questions/23330243/gnu-makefile-how-to-and-when-to-quote-strings/23332194#23332194))

**Comment by Weltraumschaf** [comment]
Houston, we have a problem!

We have this "sophsticated" find:

```make
PACKAGE_JSON_LIST				:= $(shell find "$(PROJECT_DIR)" \( \
                                   		-name .git -o \
                                   		-name .github -o \
                                   		-name .idea -o \
                                   		-name .reuse -o \
                                   		-name .vagrant -o \
                                   		-name .vscode -o \
                                   		-name bin -o \
                                   		-name docs -o \
                                   		-name LICENSES -o \
                                   		-name coverage -o \
                                   		-name dist -o \
                                   		-name node_modules -o \
                                   		-name target \) \
                                   		-prune \
                                   		-false \
                                   		-o -type f \
                                   		-iname package.json)
```

To find all NPM packages. This results in a list of paths separated by **spaces**. Later we loop over them with shell for loop, which treats **any whitespcae** for word split. First approach is to use `while read` which splits only on newline. But the paths in the list are splitted by spaces...

**Comment by Weltraumschaf** [comment]
First fixes: https://github.com/secureCodeBox/secureCodeBox/pull/1357

But IMHO this is a major problem.

**Comment by Weltraumschaf** [comment]
The whole thing is even worse... The tool checks we have at various places do not work on macOS/FreeBSD. E.g. this one:

```makefile
ifeq ($(include_guard),)
	$(error you should never run this makefile directly!)
endif
```

This works fine on GNU/Linux (tested w/ Debian Bullseye & GNU Make 4.3). But on macOS (tested w/ macOS Monteray & GNU Make 3.81 from Xcode and 4.3 from Homebrew) it fails with error (Gnu Make 3.81):

```
Makefile:8: *** commands commence before first target.  Stop.
```

error (Gnu Make 4.3):

```
Makefile:8: *** recipe commences before first target.  Stop.
```

IMHO we misuse make here. Typically such checks are done with `./configre` scripts in the C world.

**Comment by Weltraumschaf** [comment]
On a plain FreeBSD (13.1-RELEASE-p2) we have other issues, too:

```shell
[root@git ~/src/secureCodeBox]# make
make: "/root/src/secureCodeBox/Makefile" line 73: Invalid line type
make: "/root/src/secureCodeBox/Makefile" line 83: Invalid line type
make: "/root/src/secureCodeBox/Makefile" line 85: Invalid line type
make: Fatal errors encountered -- cannot continue
make: stopped in /root/src/secureCodeBox
```

The offending lines are:

```makefile
ifdef NAME...
else
...
endif
```

No idea what version of make FreeBSD uses. It uses the -v flag for Variables and can't find an option to print the version.

**Comment by Weltraumschaf** [comment]
Maybe another build tool could be a solution in the future, so for the record:

- @SebieF recommended [SCons](https://scons.org/) bc [Godot Engine](https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html) uses it.
  - My concerns: It is a build tool with "Built-in support for C, C++, D, Java, Fortran, Yacc, Lex, Qt and SWIG, and building TeX and LaTeX documents." Nothing built-in we use. IMHO this would be to another tool which is designed for something we do not do and will also result in workarounds.
- CMake is also no option bc it is simply a generator for make.
- [Task](https://taskfile.dev/) looks promising.

**Comment by Weltraumschaf** [comment]
> Make is very touchy about spaces and tabs, it treats indented lines as commands, so you need to remove them. E.g. it should be -- [SO](https://stackoverflow.com/questions/34562221/recipe-commences-before-first-target-stop).

Does not work, but only if indented with tab:

```makefile
ifeq (1,1)
    $(error SNAFU!)
endif
```

Works:

```makefile
ifeq (1,1)
$(error SNAFU!)
endif
```

Indentation with spaces will also work, but introduces mixed space indentation...

🧐🤦‍♂️🤪
