### ISSUE TITLE
Improve Docs on How to Connect Securecodebox with Elasticsearch and Kibana

### ISSUE THREAD

**Issue by byteknacker** [secureCodeBox/secureCodeBox#1376]
### Where to find the issue
There is no documentation on how to connect and set up the helm charts correctly in order to send the reports of securecodebox scans, such as zap scan results, to Elasticsearch and display it on Kibana. I tried so many hours to configure the charts correctly but to no avail. 

### Describe the issue
Since the scans are only send to minio by default and not displayed on any dashboard, it is good to have clear documentation on how to connect the charts. I can deploy kibana and elasticsearch but I do not know how to display the scan results on the dashboard.

### Suggested change
Add docs on this topic and add extensive example code for each dashboard solution, especially Elasticsearch/Kibana, also please add some screenshots of example dashboards and step by step guides to set them up. 

I need example code for the helm charts that I have to modify. It would also be great if you can just provide a complete solution with scan results sent to the Kibana dashboard out of the box with just one single helm chart and no brain work needed to set up all the different components.

**Comment by SebieF** [comment]
Hi, thank you for submitting an issue! 

We created a tutorial for your exact problem lately, please refer to it and let us know if you still experience problems: https://www.securecodebox.io/docs/how-tos/persistence-storage

**Comment by byteknacker** [comment]
Thank you so much for this! Really appreciate your time and effort. I will read the new docs and also try it out again on Monday. Will come back with some feedback.
