### ISSUE TITLE
screenshooter is not working 

### ISSUE THREAD

**Issue by Hanoos** [secureCodeBox/secureCodeBox#1386]
Thank you for the efforts,  Running the screenshooter scan, and its giving these errors 

helm chart is installed using 

helm upgrade --install screenshooter secureCodeBox/screenshooter

Endpoint defined with https:// and error returned 

*** You are running in headless mode.
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL missing
[GFX1-]: No GPUs detected via PCI
*** You are running in headless mode.
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL missing
[GFX1-]: No GPUs detected via PCI

=============

apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "screenshot-github-securecodebox.io"
spec:
  scanType: "screenshooter"
  parameters:
    - "https://github.com/secureCodeBox"

**Comment by J12934** [comment]
Hi @Hanoos 

I can't reporoduce your error.
Screenshooter is properly running and is giving me the following screenshot for the scan:

![screenshot](https://user-images.githubusercontent.com/13718901/194073804-8356af91-9fd2-46c6-b5ab-3b0c86bf3441.png)

We had a bugfix in a recent release of the screenshooter can you make sure you are on the latest version (3.15.0)?
You should be able to update using:

```bash
helm update
helm upgrade --install screenshooter secureCodeBox/screenshooter
# then restart the scan by deleting and recreating it
```

If not can you please post the output of the following commands to debug this further:

```bash
helm ls
kubectl get scan -oyaml screenshot-github-securecodebox.io
```

**Comment by Hanoos** [comment]
@J12934 - I removed the chart and reinstalled it - After re-install it appeared to work as expected   - Thanks for your help - closing
