### ISSUE TITLE
➹ Add default securityContext for included Scanner

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#140]
**Is your feature request related to a problem? Please describe.**

The secureCodeBox already supports to define custom securityContext for the scanners.
It would be nice to have default securityContexts set for every scanner which are pre-configured individually for each scanner, so that this doesn't have to be done by the users.

**Describe the solution you'd like**

The value files of the scanner should include a default configured scanType which restricts the container from features it doesn't really require to improve the security stance of the secureCodeBox.

This has already been implemented for Nmap, see: https://github.com/secureCodeBox/secureCodeBox-v2/blob/7596d3f4d9c272ba98c29aa639160bbd27e45c9a/scanners/nmap/values.yaml#L39-L52

**Comment by Weltraumschaf** [comment]
Basics, such as not allowing to run scanners as root user etc., are defined for all scanners.
