### ISSUE TITLE
Check outdated scanners runs on forks and fails permanently

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#1438]
## 🐞 Bug report

The [CI job for checking outdated scanners](https://github.com/Weltraumschaf/secureCodeBox/actions/workflows/scb-bot.yaml) runs automatically on my fork and always fails. This is quite annoying.

### Expected behavior

The CI job must not run on forks to prevent annoyed community.

**Comment by Ilyesbdlala** [comment]
Closed by #1437
