### ISSUE TITLE
SCB-Bot Opens Scanner PRs with Version "null"

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#1505]
The SCB-Bot wants to change versions to "vnull":

* https://github.com/secureCodeBox/secureCodeBox/pull/1503
* https://github.com/secureCodeBox/secureCodeBox/pull/1504

**Comment by Ilyesbdlala** [comment]
@Weltraumschaf #1509 should fix the issue. Workflow will fail when unable to fetch remote version (best guess due to connectivity issues), instead of creating a PR with version null.
