### ISSUE TITLE
I need v4.0.0 

### ISSUE THREAD

**Issue by renatosazup** [secureCodeBox/secureCodeBox#1656]
Do you already have a concrete date for version 4.0.0? I really need a feature that I contributed to the project because of compliance.

thanks.

**Comment by renatosazup** [comment]
Hi  @J12934 😄 

I need  in particular this  [Pull Request](https://github.com/secureCodeBox/secureCodeBox/pull/1526 ) 

thanks.

**Comment by rseedorff** [comment]
Finally... there it is 🙌 

https://github.com/secureCodeBox/secureCodeBox/releases/tag/v4.0.1
