### ISSUE TITLE
Amass Image Missing

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#1663]
## 🐞 Bug report

Amass image used on main (3.22.2) doesn't exist in docker hub anymore making the pipelines fail.

### Additional context

https://github.com/secureCodeBox/secureCodeBox/actions/runs/4563728846/jobs/8053198253

**Comment by Ilyesbdlala** [comment]
Fixed in https://github.com/secureCodeBox/secureCodeBox/commit/4e88e87dfb90cbe75a31bd02783b7d05e86561b3.
