### ISSUE TITLE
Get login username

### ISSUE THREAD

**Issue by cnsino** [secureCodeBox/secureCodeBox#1691]
## Using the following command the output is empty
```bash
kubectl get secret securecodebox-operator-minio -n securecodebox-system -o=jsonpath='{.data.root-user}' | base64 --decode; echo
```

**Comment by cnsino** [comment]
Users obtained using the output of this command can log in
```bash
kubectl get secret securecodebox-operator-minio -n securecodebox-system -o=jsonpath='{.data.accesskey}' | base64 --decode; echo
```
YOURACCESSKEY

**Comment by Ilyesbdlala** [comment]
> Users obtained using the output of this command can log in
> 
> ```shell
> kubectl get secret securecodebox-operator-minio -n securecodebox-system -o=jsonpath='{.data.accesskey}' | base64 --decode; echo
> ```
> 
> YOURACCESSKEY

That is true. This is a known issue and will be resolved by the coming v4 release.
See https://github.com/secureCodeBox/documentation/pull/290 for more context.
