### ISSUE TITLE
No more nikto-scanner image (or scannner with 3 n) available on dockerhub

### ISSUE THREAD

**Issue by yannschepens** [secureCodeBox/secureCodeBox#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System (please complete the following information):**

**Screenshots / Logs**

**Additional context**

**Comment by fuhrmeistery** [comment]
Thank you for letting us know. We will take a look at it

**Comment by J12934** [comment]
Hey @yannschepens,
Thanks again for reporting this 🙌
We've now added nikto to be automatically build.
I've just noticed that there was also a typo in the image name of the ScanType. (#174)

This can be worked around (untill our next release) by overwriting the image via name:
`helm install nikto secureCodeBox/nikto --set="image.repository=securecodebox/scanner-nikto"`

**Comment by yannschepens** [comment]
Hey @J12934,

Thank you for the image and the tips ;)
