### ISSUE TITLE
helm repo : https://charts.securecodebox.io not accessable

### ISSUE THREAD

**Issue by skc-chy** [secureCodeBox/secureCodeBox#1728]
### Describe the bug
I am trying to install securecodebox into K8 through helm chart. But the helm repo : https://charts.securecodebox.io is not accessible. 

### Steps To Reproduce

1. Open browser
2. type 'https://charts.securecodebox.io' in address bar
3. see error

### System (please complete the following information):

 - secureCodeBox Version/Release : latest
 - OS: Windows
 - Kubernetes Version [command: `kubectl version`] : v1.25.9
 - Docker Version [command: `docker -v`] : 23.0.5
 - Browser [e.g. chrome, safari, firefox,...] : Chrome

**Comment by J12934** [comment]
Hi @skc-chy 
Thanks for reporting this 🙌
Will try to get this resolved ASAP, but might take us a bit. 

We had a holiday in Germany on Thursday, so nobody has been working since then 😅 (Entire SCB core team is in Germany)

**Comment by J12934** [comment]
@skc-chy should be resolved now :)
We had a problem with the ingress on the k8s cluster the chart registry is running on.

Thank you again for reporting this 🙌
