### ISSUE TITLE
Failed to install the new released zap, zap-advanced

### ISSUE THREAD

**Issue by xyfleet** [secureCodeBox/secureCodeBox#1756]
## 🐞 Bug report
I tried to install nmap, zap, zap-advanced chart (4.0.1) and failed. (I installed the secureCodeBox Operator chart(4.0.1) successfully.)
Not sure why can't I install nmap, zap and zap-advanced and more.
### Describe the bug
```
 Error: error validating "": error validating data: ValidationError(ScanType.spec.jobTemplate.spec): unknown field "suspend" in io.securecodebox.execution.v1.ScanType.spec.jobTemplate.spec
│
│   with module.securecodebox.helm_release.zap-advanced,
│   on ../../modules/securecodebox/main.tf line 186, in resource "helm_release" "zap-advanced":
│  186: resource "helm_release" "zap-advanced" {
```

### Steps To Reproduce
```
resource "helm_release" "zap" {
  repository = "https://charts.securecodebox.io/"

  name       = "zap"
  chart      = "zap"
  version    = "4.0.1"
  namespace  = "default"
```

### Expected behavior
Expected to install the new version of Zap for scanning purpose.

**Comment by J12934** [comment]
Hi, thank you for reporting this 🙌
I can't reproduce it. For me the install is going through fine on both on k8s 1.27 and 1.24.
Which kubernetes version are you using?

**Comment by J12934** [comment]
One thing of note too. If you haven't updated your secureCodeBox Crds in a while they might also be missing the job.spec.suspend field. They were added with k8s 1.21, not sure which SCB version updated the CRDs to that but if they are really old they might be missing the field.

You should be able to update them to 4.0.1 by running:

```sh
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/cascading.securecodebox.io_cascadingrules.yaml
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/execution.securecodebox.io_parsedefinitions.yaml
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/execution.securecodebox.io_scancompletionhooks.yaml
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/execution.securecodebox.io_scans.yaml
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/execution.securecodebox.io_scantypes.yaml
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.1.0/operator/crds/execution.securecodebox.io_scheduledscans.yaml
```

**Comment by xyfleet** [comment]
@J12934 Thank you so much. You are right, I need to manually update these crds.
