### ISSUE TITLE
Helm install command leads

### ISSUE THREAD

**Issue by danapr** [secureCodeBox/secureCodeBox#1770]
Hi,
trying to install swagger-petsore on `kind` using `helm`. When using the command on the README
`helm upgrade --install swagger-petstore secureCodeBox/swagger-petstore`
I'm getting this error:
Error: repo secureCodeBox not found

What am I doing wrong? Or is it a bug?
Thank you :)

**Comment by danapr** [comment]
use this command before:
`helm repo add secureCodeBox https://charts.securecodebox.io`

**Comment by J12934** [comment]
Hi 👋 
Yes that's exactly what's needed.
This raises a valid point, i guess the repo should be included in all docs of all components. Will update the docs to fix this 👍
