### ISSUE TITLE
parse error at amass parser

### ISSUE THREAD

**Issue by Alideniz** [secureCodeBox/secureCodeBox#1804]
### Describe the bug
Amass parser doesn't work properly. It doesn't show the sources of domain. I found multiple typo on the codebase. Amass returns `sources` but parser tries to parse with `source`

### Expected behavior
It should returns sources of subdomains.

### System (please complete the following information):
secureCodeBox v4.0.1

**Comment by J12934** [comment]
Hi this is now fixed and release with secureCodeBox 4.1.0 :)
