### ISSUE TITLE
Implement Helm charts unit-tests

### ISSUE THREAD

**Issue by Ilyesbdlala** [secureCodeBox/secureCodeBox#1814]
### Is your feature request related to a problem?

Changes that break the helm charts, do not fail our CI. This caused the need for the patch release [v3.15.1](https://github.com/secureCodeBox/secureCodeBox/releases/tag/v3.15.1). In this case the megalinter linting broke the templating process but was not reflected in our CI.
### Describe the solution you'd like 

Create helm charts unit-tests, that test, among others, the templating process.
### Additional context

~~https://helm.sh/docs/topics/chart_tests/~~
https://github.com/helm-unittest/helm-unittest

**Comment by J12934** [comment]
Mh sorry Ilyes, the helm test command I sent you is not for unit tests, I misremembered that. 
Helm test is to test if a installed helm release is functioning correctly.

There is a third party tool to unit test helm templates: https://github.com/helm-unittest/helm-unittest
