### ISSUE TITLE
Amass Scanner Scan fails

### ISSUE THREAD

**Issue by Zero3141** [secureCodeBox/secureCodeBox#1826]
### Describe the bug
The amass scanner fails to execute. In the container logs, one can see an error. No file is written, so consequently, the parser fails as well.

### Steps To Reproduce
1. Install latest amass image with `helm upgrade --install amass secureCodeBox/amass`
2. Submit example scan with `kubectl apply -f scanners/amass/examples/secureCodeBox.io/scan.yaml`
3. In the logs of `caffix/amass:v4.0.3` in `scan-amass-securecodebox.io-...` you see the error `flag provided but not defined: -json`

### Expected behavior
The amass container performs a scan

### System (please complete the following information):
 - secureCodeBox Version/Release: 4.0.1 (operator)
 - OS: Ubuntu 20.04 (on WSL)
 - Kubernetes Version: v1.27.4
 - Docker Version: 24.0.4, build 3713ee1

#### Scanner
```
flag provided but not defined: -json
Stream closed EOF for default/scan-amass-securecodebox.io-c5sq9-bjqzz (amass)
```

#### Lurker
```
2023/07/24 11:23:58 Starting lurker
2023/07/24 11:23:58 Waiting for main container 'amass' to complete
2023/07/24 11:23:58 After scan is completed file '/home/securecodebox/amass-results.jsonl' will be uploaded to 'securecodebox-operator-minio.securecodebox-system.svc.cluster.local'
2023/07/24 11:23:58 Waiting for maincontainer to exit
2023/07/24 11:23:58 Main Container exited. Lurker will end as well.
2023/07/24 11:23:58 Uploading result files.
2023/07/24 11:23:58 Uploading /home/securecodebox/amass-results.jsonl
2023/07/24 11:23:58 File has a size of 0 bytes
2023/07/24 11:23:58 Failed to read file
2023/07/24 11:23:58 open /home/securecodebox/amass-results.jsonl: no such file or directory
Stream closed EOF for default/scan-amass-securecodebox.io-c5sq9-bjqzz (lurker)
```

**Comment by Zero3141** [comment]
Seems to be a bug/change in amass as the error also occurs when launching the container directly.

Steps for amass according to their [Docker Container setup](https://github.com/owasp-amass/amass/tree/master#docker-container):
1. Pull the Docker image by running `docker pull caffix/amass`
2. Without the json flag it works `docker run -v OUTPUT_DIR_PATH:/.config/amass/ caffix/amass enum -d owasp.org`
3. With json flag it does **not** works `docker run -v OUTPUT_DIR_PATH:/.config/amass/ caffix/amass enum -json a.json -d owasp.org`

In their [User Guide](https://github.com/owasp-amass/amass/blob/master/doc/user_guide.md), only the `db` Subcommand has the json flag. The `enum` Subcommand (which we use) only has the `-o` flag for output into a file

**Comment by Weltraumschaf** [comment]
Caused by https://github.com/secureCodeBox/secureCodeBox/pull/1821 (https://github.com/secureCodeBox/secureCodeBox/pull/1830)
