### ISSUE TITLE
Scan containers errored

### ISSUE THREAD

**Issue by TripShade** [secureCodeBox/secureCodeBox#184]
**Describe the bug**
I ran a wpscan after installing the scanner it errored. Then verified if it wasn't my config by running your examples they also errored other scanners work as expected.

**To Reproduce**
1. Run wpscan for example.com

**Expected behavior**
Match the example results or no scan container error

**Screenshots**

**Desktop (please complete the following information):**
macbook pro with 32gb ram and i9
macOS 10.15.7
docker engine v19.03.13 (docker desktop app)
kubernetes v1.18.8 (docker desktop app)

**Additional context**
container logs are not available.

// kubectl describe scan
Name:         wpscan-www.example.com
Namespace:    default
Labels:       <none>
Annotations:  API Version:  execution.securecodebox.io/v1
Kind:         Scan
Metadata:
  Creation Timestamp:  2020-10-27T09:35:36Z
  Finalizers:
    s3.storage.securecodebox.io
  Generation:  1
  Managed Fields:
    API Version:  execution.securecodebox.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:parameters:
        f:scanType:
    Manager:      kubectl
    Operation:    Update
    Time:         2020-10-27T09:35:36Z
    API Version:  execution.securecodebox.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"s3.storage.securecodebox.io":
      f:status:
        .:
        f:errorDescription:
        f:findingDownloadLink:
        f:findings:
          .:
          f:severities:
        f:rawResultDownloadLink:
        f:rawResultFile:
        f:rawResultType:
        f:state:
    Manager:         manager
    Operation:       Update
    Time:            2020-10-27T09:41:44Z
  Resource Version:  652009
  Self Link:         /apis/execution.securecodebox.io/v1/namespaces/default/scans/wpscan-www.example.com
  UID:               e71335a2-0d33-4487-a835-5bdb7a7ae24f
Spec:
  Parameters:
    --url
    https://www.example.com
    -e
    vp
    --plugins-detection
    mixed
    --api-token
    AAAAABBBBBCCCCCDDDDEEEEEEE
  Scan Type:  wpscan
Status:
  Error Description:      Failed to run the Scan Container, check k8s Job and its logs for more details
  Finding Download Link:  http://securecodebox-operator-minio.default.svc.cluster.local:9000/securecodebox/scan-e71335a2-0d33-4487-a835-5bdb7a7ae24f/findings.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YOURACCESSKEY%2F20201027%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201027T093536Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=f3988744a5d6142e264cbc1c62c6899d54f6b7552cc0c58f5db40fb4fe2d0c60
  Findings:
    Severities:
  Raw Result Download Link:  http://securecodebox-operator-minio.default.svc.cluster.local:9000/securecodebox/scan-e71335a2-0d33-4487-a835-5bdb7a7ae24f/wpscan-results.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YOURACCESSKEY%2F20201027%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201027T093536Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=cab7abf913bbb27793779316bb076222326582922cb98165123f1ac1e50477da
  Raw Result File:           wpscan-results.json
  Raw Result Type:           wpscan-json
  State:                     Errored
Events:                      <none>

// kubectl describe job
wpk6
Name:           scan-wpscan-www.example.com-hwpk6
Namespace:      default
Selector:       controller-uid=8ade03f2-8cee-4297-a933-66478c0164e7
Labels:         securecodebox.io/job-type=scanner
Annotations:    <none>
Controlled By:  Scan/wpscan-www.example.com
Parallelism:    1
Completions:    1
Start Time:     Tue, 27 Oct 2020 10:35:36 +0100
Pods Statuses:  0 Running / 0 Succeeded / 1 Failed
Pod Template:
  Labels:           controller-uid=8ade03f2-8cee-4297-a933-66478c0164e7
                    job-name=scan-wpscan-www.example.com-hwpk6
  Annotations:      securecodebox.io/job-type: scanner
                    sidecar.istio.io/inject: false
  Service Account:  lurcher
  Containers:
   wpscan:
    Image:      wpscanteam/wpscan:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      wpscan
      -o
      /home/securecodebox/wpscan-results.json
      -f
      json
      --url
      https://www.example.com
      -e
      vp
      --plugins-detection
      mixed
      --api-token
      AAAAABBBBBCCCCCDDDDEEEEEEE
    Environment:  <none>
    Mounts:
      /home/securecodebox/ from scan-results (rw)
   lurcher:
    Image:      docker.io/securecodebox/lurcher:v2.1.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --container
      wpscan
      --file
      /home/securecodebox/wpscan-results.json
      --url
      http://securecodebox-operator-minio.default.svc.cluster.local:9000/securecodebox/scan-e71335a2-0d33-4487-a835-5bdb7a7ae24f/wpscan-results.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YOURACCESSKEY%2F20201027%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201027T093536Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=bde3b83940b036607afe1b96dac5e9265fb425ebcbc5e4dad99fc2aa297dae9b
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     20m
      memory:  20Mi
    Environment:
      NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /home/securecodebox/ from scan-results (ro)
  Volumes:
   scan-results:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      25m   job-controller  Created pod: scan-wpscan-www.example.com-hwpk6-tddrp
  Normal   SuccessfulDelete      19m   job-controller  Deleted pod: scan-wpscan-www.example.com-hwpk6-tddrp
  Warning  BackoffLimitExceeded  19m   job-controller  Job has reached the specified backoff limit

**Comment by TripShade** [comment]
You were right this container also fails.
Scan Aborted: The url supplied 'anonymous' seems to be down (Couldn't connect to server). 

It must be an issue with our bunkerized wordpress image (I might even consider it to be a feature lol).
Thx for the fast response :)

**Comment by J12934** [comment]
Okay nice 👍
Not problem
