### ISSUE TITLE
Amass unavailable in SCB 4.0.1 Release

### ISSUE THREAD

**Issue by Ilyesbdlala** [secureCodeBox/secureCodeBox#1847]
### Describe the bug

SCB on currently latest release v4.01 is unable to run amass scans due to the following reasons:

-  Amass v4.x has breaking changes (See #1833) so upgrading was not quickly possible.
-  Amass deletes periodically (~monthly) their docker images. This means that the version v3.23.2 that is included in SCB v4.0.1 is no longer available. Only v3.x version that is still available in DockerHub is v3.23.2 
- Amass v3.23.2 Docker image currently has an issue where the container does not exit correctly, resulting into the scan never reaching the `Finished` State. See https://github.com/owasp-amass/amass/issues/918

A notice has been added here: https://github.com/secureCodeBox/secureCodeBox/pull/1848

### Steps To Reproduce

Run an amass scan
### Expected behavior

- An Amass scan should run correctly.
- Notice https://github.com/secureCodeBox/secureCodeBox/pull/1848 should be removed

### System (please complete the following information):

 - secureCodeBox Version/Release: v4.0.1

**Comment by J12934** [comment]
fixed in 4.1.0
