### ISSUE TITLE
Deprecate ZAP Advanced and ZAP Baseline

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#1851]
We do not want to maintain this anymore, in favor of ZAP Automaton framework.

**Comment by Weltraumschaf** [comment]
Depends on:https://github.com/secureCodeBox/documentation/issues/338

**Comment by Weltraumschaf** [comment]
We can set Helm charts deprecated: https://helm.sh/docs/topics/charts/#deprecating-charts

**Comment by moxli** [comment]
@Weltraumschaf I notice when using the automation framework in additon with DefectDojo that the importer used there is not the ZAP scan one but rather the Generic findings import.
Is this intentional or something where compatibility is missing with SecureCodeBox or DefectDojo?

**Comment by Weltraumschaf** [comment]
Hi @moxli, 

sorry, I completely missed your message here 🙈

**Comment by Weltraumschaf** [comment]
Resolved by https://github.com/secureCodeBox/secureCodeBox/issues/1902
