### ISSUE TITLE
Stub Generator For New Scanner

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#186]
**Is your feature request related to a problem? Please describe.**

As a developer I would like to have a stub generator for new scanners that will create all necessary files with a basic configuration to simplify the integration process. 

**Describe the solution you'd like**

There is some kind of cli tool that can generate a stub for a new scanner will every file needed.

**Describe alternatives you've considered**

Creating a stub using helm but this will create files and directories that are not needed but misses files that are.
Using Helm Starter Charts is not sufficient because files listed in `.helmignore` are also ignored in the creation process.

See #189

**Comment by J12934** [comment]
Already added by `create-new-scanner` make target which uses the https://github.com/secureCodeBox/secureCodeBox/tree/main/.templates/new-scanner folder as a template
