### ISSUE TITLE
Add breaking changes from major versions to the documentation

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1905]
The documentation website should contain information on breaking changes between major versions. A good starting point would be the [UPGRADING.md](https://github.com/secureCodeBox/secureCodeBox/blob/main/UPGRADING.md) file from the main repo.

**Comment by Weltraumschaf** [comment]
We have breaking changes in UPGRADING.md and will move this into the documentation, since we've combined the docs and main repo. See https://github.com/secureCodeBox/secureCodeBox/issues/1908
