### ISSUE TITLE
Add a CLA or DCO to the project

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#193]
Add a Contributor License Agreement (CLA) or Developer Certificate of Origin (DCO) to the project

Background Informations:
- https://medium.com/@flamefew/clas-and-using-dco-clearly-e46b09a4c048
- https://opensource.com/article/18/3/cla-vs-dco-whats-difference

Todos:

- [ ]  ~~Ask apache foundation~~
- [ ]  ~~Ask a lawyer~~
- [x]  Ask https://fsfe.org/

**Comment by Weltraumschaf** [comment]
This relates to #194: If we choose DCO we should use license headers in every file. That's stated by one of linked article.

**Comment by fuhrmeistery** [comment]
To enable us to use DCO we will need to:
- Add License Headers to each file
- Require every commit in every new PR to include "Signed-off-by" (could be automated by [Probot](https://probot.github.io/apps/dco/))

Stated by the article above we may additionally need:
- A `CONTRIBUTORS` file
- A DCO Copy with SPDX Licenses that are considered appropriate

**Comment by Weltraumschaf** [comment]
Mailed the FSFE. Today they requested the mail translated in English :/

**Comment by Weltraumschaf** [comment]
I got the first answer from FSFE Legal Coordinator:

>> 1. Why is it necessary to add a license header to each file? We know that lot of OSS project do this, but we didn't found a solid legal reason which explains why just one single "license.txt" is not sufficient.
>
> This is not strictly a legal requirement, however it is a practical one,
> and the FSFE has found to be good practice for downstream projects. In
> many software projects there might be more than one license at play; not
> only the license you choose to cover your project, but also the licenses
> that apply to code or components that are reused into your project. In
> many situations, these may not be the same licenses.
> 
> For example, let's say that a project (Project A) chooses to use the MIT
> license overall. However, it reuses components that are covered by
> another license, for example, the Apache license. These components in
> Project A's repository will therefore have different copyright holders,
> and a different applicable license, than the rest of the files. It is
> therefore very useful to mark out for each file who the copyright owner
> and which license applies. If a developer wants to reuse components or
> source code from Project A later down the line, they may not be able to
> immediately tell that the Apache components have a different copyright
> holder and are licensed under the Apache license. They may instead
> assume that it is licensed under the MIT license, and that the copyright
> belongs to the Project A's developers. Having the copyright and license
> information readily available in each file reduces this kind of
> confusion, and helps to promote accurate license compliance in the
> community by making it easier for developers to reuse Free Software.
> 
> We have more information about how best to do this on our REUSE
> initiative website here: https://reuse.software/
>
>> 2. How does this work with binary files (eg. jpg, png, etc.) or files which does not allow comments (eg. JSON)?
>
> Generally, if a file is not a plain text file or does not permit the
> inclusion of comments, we recommend that the comment header be in an
> adjacent file of the same name with the additional extension .license
> (example: cat.jpg.license if the original file is cat.jpg). While this
> can be a tedious process, it allows for such files to be scanned and
> rendered machine-readable by license tools.
> 
> Nevertheless, there are situations where this is impractical. For
> example, if you have a directory containing many files, such as a
> directory containing 100 image files or more, it may not be easy or
> practical to edit every file to contain a header, and to create adjacent
> files for each file. While doing this would be ideal, there is an
> alternative. By creating the file .reuse/dep5 in the root of your
> project, you can bulk-license a directory. For example:
> 
>     Format:
> https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/   
>    Upstream-Name: my-project
>    Upstream-Contact: Jane Doe <jane@example.com>
>    Source: https://git.example.com/jane/my-project
>
>    Files: resources/img/*
>    Copyright: 2017 Jane Doe <jane@example.com>
>    License: CC-BY-4.0
>
>    Files: resources/vid/*
>    Copyright:     2017 Jane Doe <jane@example.com>
>                          2017 John Doe <john@example.com>
>    License: CC0-1.0
>
>> 3. Are we completely wrong how we understand DCO?
>
> As your question on CLAs and DCOs is a bit more legally complex, I will
> forward your inquiry to our License Questions, who are mostly lawyers
> dealing with Free Software licensing issues, and can give you a more
> informed answer than I can. I will get back to you as soon as they have
> discussed this, which may take a few more days. In the meantime, thank
> you for your patience, and I will speak with you soon!

**Comment by Weltraumschaf** [comment]
Interesting article about why you should not sign a CLA: https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

**Comment by Weltraumschaf** [comment]
The FSFE didn't respond to answer the last question. Since we receive the first contributions from the community we must go ahead. We decided to choose DCO which seems more afordable.

**Comment by Weltraumschaf** [comment]
- [SPDX License List](https://spdx.org/licenses/)
- [REUSE Spec](https://reuse.software/spec/)

**Comment by Weltraumschaf** [comment]
Should we add maintainers and contributors in separate files as suggested by @fuhrmeistery [here](https://github.com/secureCodeBox/secureCodeBox/pull/441)?
