### ISSUE TITLE
Check docs for all scanners for correctness: Amass

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#1934]
Part of the effort to sanity-check all documentation.

## Scanner Sanity-Check:
- [x] Sanity Check if the existing documentation is understandable and useful for you as a (first time) user
- [x] Ensure the general chart/scanner description is up to date and consistent to other scanners
   * `./scanner/NAME/.helm-docs.gotmpl -> {{- define "extra.chartAboutSection" -}}`
- [x] Ensure the baseline scanner configuration is up to date and consistent to other scanners
   * `./scanner/NAME/.helm-docs.gotmpl -> {{- define "extra.scannerConfigurationSection" -}}`
- [x] Ensure there is at minimum one scan example with the following files:
   * Example Scan File: `./scanner/NAME/examples/EXAMPLE-NAME/scan.yaml`
   * Example Scan Result File: `./scanner/NAME/examples/EXAMPLE-NAME/findings.yaml`
- [x] Ensure the docs files are generated correct and are up to date (sometimes the automated helm-docs update via SCB-Bot failed to update the docs correctly)
   * `./scanner/NAME/readme.md`
   * `./scanner/NAME/docs/README.ArtifactHub.md`
   * `./scanner/NAME/docs/README.DockerHub-Parser.md`
   * Optional, only if a dedicated scanner image is defined:`./scanner/NAME/docs/README.DockerHub-Scanner.md`
   
## Additional Context:
- SCB Scanner Documentation (based on the above markdown files): https://docs.securecodebox.io/docs/scanners
- SCB DockerHub Images (with description based on docs for each image): https://hub.docker.com/u/securecodebox/
- SCB Artifact Helm Charts: https://artifacthub.io/packages/search?org=securecodebox

**Comment by Ilyesbdlala** [comment]
Resolved in #1864
