### ISSUE TITLE
Consider if we need license headers in every file

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#194]
We see two options:

1. Put one single license file into our repositories.
2. Put the license text at the beginning of each source file.

Most OSS projects use option 2. but we do not know why.  The Option 1. is way easier.

See #193

**Comment by rseedorff** [comment]
Hi @Weltraumschaf, 
in my opinion we can close this issue since its implemented now. Or is anything missing here?
