### ISSUE TITLE
No images found for ZAP and Nikto charts with version 4.1.0

### ISSUE THREAD

**Issue by moxli** [secureCodeBox/secureCodeBox#1997]
### Describe the bug
For the new release 4.1.0 there seem to be no images with the tag 4.1.0 available for the Zap and Nikto charts.

### Steps To Reproduce
1. Install the SecureCodeBox operator Helm chart in version 4.1.0
2. Install the ZAP or Nikto scanner Helm chart in version 4.1.0
3. Create a ZAP or Nikto scan
4. See the error in the pod events

### Expected behavior
I expect the Helm chart to work out of the box with an available image version.

### System (please complete the following information):
 - secureCodeBox Version/Release: 4.1.0
 - OS: Linux
 - Kubernetes Version: v1.24.14-gke.2700
 - Docker Version: N/A

### Screenshots / Logs

Helm chart versions
```
helm search repo secureCodeBox | grep -e Nikto -e ZAP
secureCodeBox/nikto                             4.1.0           2.5.0           A Helm chart for the Nikto security scanner tha...
secureCodeBox/zap                               4.1.0           2.13.0          A Helm chart for the OWASP ZAP security scanner...
secureCodeBox/zap-advanced                      4.1.0           2.13.0          A Helm chart for the OWASP ZAP (extended with a...
```

**Pod Event Log**
```
  Normal   Pulling    42s (x4 over 2m17s)  kubelet            Pulling image "docker.io/securecodebox/parser-zap:4.1.0"
  Warning  Failed     38s (x4 over 2m10s)  kubelet            Failed to pull image "docker.io/securecodebox/parser-zap:4.1.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/securecodebox/parser-zap:4.1.0": failed to resolve reference "docker.io/securecodebox/parser-zap:4.1.0": docker.io/securecodebox/parser-zap:4.1.0: not found
  Warning  Failed     38s (x4 over 2m10s)  kubelet            Error: ErrImagePull
  Warning  Failed     15s (x6 over 2m10s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3s (x7 over 2m10s)   kubelet            Back-off pulling image "docker.io/securecodebox/parser-zap:4.1.0"
```

The image tag seems to be mapped to the Helm chart version.
```
Containers:
  parser:
    Container ID:
    Image:         docker.io/securecodebox/parser-zap:4.1.0
```

Installation with Terraform and Helm
```
resource "helm_release" "securecodebox-nikto" {
  name       = "securecodebox-nikto"
  repository = "https://charts.securecodebox.io"
  chart      = "nikto"
  namespace  = kubernetes_namespace_v1.securecodebox.metadata[0].name
  version    = "4.0.1"

  values = [
    <<-EOF
    parser:
      tolerations:
      - key: "instance_type"
        value: "preemptible"
        effect: "NoSchedule"
    scanner:
      tolerations:
      - key: "instance_type"
        value: "preemptible"
        effect: "NoSchedule"
    EOF
  ]
```

### Additional context
My provided example is from the parser because after noticing the issue at first I downgraded the ZAP and Nikto charts to version 4.0.1 which fixed the image pull issue. This left the broken scans, which were started with the version 4.1.0, running and they are still trying to parse the results.

The same happens with the scanner pod though.

**Comment by J12934** [comment]
Hi @moxli 

Thanks for pointing this out 👍 
Had some problems in the 4.1.0 release (docker hub service disruption while the build was running)

Zap (and Trivy) parsers are now build and are present in docker hub.

For nikto i could not reproduce the issue. The parser has been there since the release: https://hub.docker.com/layers/securecodebox/parser-nikto/4.1.0/images/sha256-73e1cf8d2234b7eec713d25389c7f415d75d1fbbf3b148ebdfc713cd8c0c8cdb?context=repo

Can you try nitko again, and if it still doesn't work post the error you are getting there?

**Comment by moxli** [comment]
@J12934 Thank you! :) 

Yes the ZAP image is available now.

I must have connected two issues into one, the Nikto image was not missing sorry ^^
