### ISSUE TITLE
Why only /documentation configured for npm in Dependabot?

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#2201]
In our [Dependabot config](https://github.com/secureCodeBox/secureCodeBox/blob/23fe5be41afd5819dc2485b90c772da721622f2f/.github/dependabot.yml#L13) we have only the path `/documentation` configured for the ecosystem "npm". This seems to be wrong. Maybe this happens by accident due to the repo merge and worked beforehand by default.

**Comment by raghav1030** [comment]
Hey @Weltraumschaf , I am willing to take this on. We can set the directory path to '/' which is the root directory, obviously where our npm package resides. However, regarding what you mentioned in [this issue](#2235), I believe we can opt to not use the config explicitly for configuring Dependabot, as all the configurations mentioned in the [Dependabot config](https://github.com/secureCodeBox/secureCodeBox/blob/23fe5be41afd5819dc2485b90c772da721622f2f/.github/dependabot.yml#L13) resonate as default settings.

**Comment by raghav1030** [comment]
> Hi @raghav1030,
> 
> we do not only have npm in the root. We have various ecosystems (npm, Gradle, Go, Docker, GH Actions etc.) in sub dirs. So we want to catch them all. AFAIUY we can simply remove the config, since the defaults will do this?
> 
> Feel free to provide a PR. Please read our [contributing readme](https://github.com/secureCodeBox/secureCodeBox/blob/main/CONTRIBUTING.md) and add your DCO please.

Hey @Weltraumschaf, Just to clarify, I need to make a PR into the contributors.md file to write up my name in the contributors list only in order to add my DCO, right?

**Comment by Weltraumschaf** [comment]
> Hey @Weltraumschaf, Just to clarify, I need to make a PR into the contributors.md file to write up my name in the contributors list only in order to add my DCO, right?

Yes, that's write. Also you need to configure the sign-off tag as alias in Git for your commit messages, unless you want to pass the always the `-s` option. You can see an example in my [dotfiles](https://github.com/Weltraumschaf/dotfiles/blob/master/src/dotfiles/_gitconfig#L61), but this is optional.

> Also, could you please suggest a way for me to test Dependabot without merging it into the main branch?

Honestly, we have not that much experience with Dependabot.That's the reason we have this "exploration" issue. Maybe you can configure Dependabot in your own fork. Maybe @J12934 or @Ilyesbdlala has an idea?

**Comment by Weltraumschaf** [comment]
@Ilyesbdlala 👀

**Comment by Ilyesbdlala** [comment]
Clarification provided in https://github.com/secureCodeBox/secureCodeBox/issues/2235#issuecomment-2485204631.
And the limitation of only checking /documentation should have been already resolved in 

- https://github.com/secureCodeBox/secureCodeBox/pull/2448

This had however the side effect that docusarus updates no longer work, which I am attempting to fix through:

- https://github.com/secureCodeBox/secureCodeBox/pull/2766
