### ISSUE TITLE
Migrate to new Nikto JSON Format

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#2220]
Nikto has recently changed their JSON format on their primary git branch.
The json format in the proper nikto 2.5.0 release is broken under certain conditions so we should migrate back to the main branch soon.

**Comment by moxli** [comment]
@J12934 FYI DefectDojo has just released their update to support the new format yesterday:
https://github.com/DefectDojo/django-DefectDojo/releases/tag/2.31.0

**Comment by J12934** [comment]
Ah good. I've opened a pr to chagne it on our side.
Hoping to be able to do a SCB release either this or next week to ensure we are properly update to date on our side too.
