### ISSUE TITLE
Do we need the Dependabot config at all?

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#2235]
Do we really need `.github/dependabot.yml` and name all ecosystems to check or can we simply remove the config and Dependabot will scan everything by default?

**Comment by Weltraumschaf** [comment]
Relates to https://github.com/secureCodeBox/defectdojo-client-java/issues/114

**Comment by Weltraumschaf** [comment]
@Ilyesbdlala 👀

**Comment by Ilyesbdlala** [comment]
We use a Dependabot Config mainly to be able to group together NPM updates of the same dependency but for different packages, i.e. `package.json`.  We don't want to have 10 different PRs for the same dependency that we have in different location. 
Also, Docusaurus packages can only be updated together at the same time to work, so grouping them is necessary. We had to close the generated PRs and do it manually in the past.
