### ISSUE TITLE
API Reference site Not Found

### ISSUE THREAD

**Issue by borovskimateusz** [secureCodeBox/secureCodeBox#2268]
### Where to find the issue
I try to read API Reference linked in website docs, links provide to:
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#volume-v1-core 

### Describe the issue
The API Reference docs respond with Not Found 
[
<img width="811" alt="Screenshot 2024-02-08 at 12 53 59" src="https://github.com/secureCodeBox/secureCodeBox/assets/108801111/309f8b85-f50b-4012-8c12-4e2cee06fc1b">
](url)

**Comment by Weltraumschaf** [comment]
Hi @borovskimateusz,

thanks for submitting this issue. We will discuss this in the team.
