### ISSUE TITLE
"NullPointerException" error when sending kubeaudit scan results to DefectDojo

### ISSUE THREAD

**Issue by danil-smirnov** [secureCodeBox/secureCodeBox#2272]
### Describe the bug

We scan Kubernetes cluster using `kubeaudit` scanner and the hook `secureCodeBox/persistence-defectdojo` fails with the following error:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at io.securecodebox.persistence.util.DescriptionGenerator.generate(DescriptionGenerator.java:30)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.createTest(VersionedEngagementsStrategy.java:266)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:93)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:43)
```
### Steps To Reproduce

Run trivy scan with the following yaml:
```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "kubeaudit-all-1"
spec:
  scanType: "kubeaudit"
```

Check if the hook `persistence-defectdojo` sucсeeds.

### Expected behavior

The hook should succeed.

### System (please complete the following information):

- operator-4.3.0
- kubeaudit-4.3.0
- persistence-defectdojo-4.3.0

Google Kubernetes Engine

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10-gke.1101000", GitCommit:"375ed214cfa092ed25d2472c1709db5d7dcda078", GitTreeState:"clean", BuildDate:"2023-11-06T09:23:17Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Weltraumschaf** [comment]
Hi @danil-smirnov,

thanks for submitting this issue. We'll investigate this.

**Comment by Weltraumschaf** [comment]
@J12934 [here](https://github.com/secureCodeBox/secureCodeBox/blob/dc40c1041c80e0ff3e16664807010435d136eb09/hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/util/DescriptionGenerator.java#L30) the NPE is thrown bc the ScanSpec [parameters](https://github.com/secureCodeBox/secureCodeBox/blob/dc40c1041c80e0ff3e16664807010435d136eb09/hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanSpec.java#L41) is `null`. You introduced this with commit 163df96381a9c145c619210c2dd0a0cb6ed205ef.

I've no idea what the conditions are that this property may be null. Since this looks more or less like generating some informational message, I suggest to not require the value not null, but default to empty list instead.

**Comment by Weltraumschaf** [comment]
> @J12934 [here](https://github.com/secureCodeBox/secureCodeBox/blob/dc40c1041c80e0ff3e16664807010435d136eb09/hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/persistence/util/DescriptionGenerator.java#L30) the NPE is thrown bc the ScanSpec [parameters](https://github.com/secureCodeBox/secureCodeBox/blob/dc40c1041c80e0ff3e16664807010435d136eb09/hooks/persistence-defectdojo/hook/src/main/java/io/securecodebox/models/V1ScanSpec.java#L41) is `null`. You introduced this with commit [163df96](https://github.com/secureCodeBox/secureCodeBox/commit/163df96381a9c145c619210c2dd0a0cb6ed205ef).
> 
> I've no idea what the conditions are that this property may be null. Since this looks more or less like generating some informational message, I suggest to not require the value not null, but default to empty list instead.

We clarified this today in a meeting. It seem to be by design that this given value may be `null` and the null check was added by accident.

I work on a patch which defaults to an empty string when the requested properties are `null`.
