### ISSUE TITLE
Support Google Cloud Storage as an object storage

### ISSUE THREAD

**Issue by danil-smirnov** [secureCodeBox/secureCodeBox#2276]
### Is your feature request related to a problem?
As users of the Google Cloud Platform, we would like to leverage its cloud object storage in the same way AWS S3 is used.

### Describe the solution you'd like
We'd like to have a Google Cloud Storage support in secureCodeBox.

**Comment by danil-smirnov** [comment]
I've found how to use it, maybe documentation could be improved

**Comment by Weltraumschaf** [comment]
Hi @danil-smirnov,

if you have ideas how to improve the documentation, we're happy to review your PR.
