### ISSUE TITLE
NodeSelector configuration not working as documented in SecureCodeBox v4.4.0

### ISSUE THREAD

**Issue by Alon-Katz** [secureCodeBox/secureCodeBox#2328]
### Describe the bug
SecureCodeBox v4.4.0 was reported to support nodeSelector in the Operator, Parsers, and Scanners as per [PR #2254](https://github.com/secureCodeBox/secureCodeBox/pull/2254). However, it does not seem to work as expected. Attempting to use the simplest example:

`helm upgrade --install new-scanner secureCodeBox/gitleaks --set parser.nodeSelector.disktype=ssd`
results in the following warning and message:

```
W0303 14:17:40.267438 7536 warnings.go:70] unknown field "spec.nodeSelector"
Release "new-scanner" has been upgraded. Happy Helming!
NAME: new-scanner
LAST DEPLOYED: Sun Mar 3 14:17:40 2024
NAMESPACE: default
STATUS: deployed
REVISION: 9
TEST SUITE: None
```

### Steps To Reproduce
Run the following command:
`helm upgrade --install new-scanner secureCodeBox/gitleaks --set parser.nodeSelector.disktype=ssd`
Observe the error output.

### Expected behavior
If the release notes indicate support for nodeSelector, then setting a value for nodeSelector should be functional without resulting in an error.

### System (please complete the following information):
secureCodeBox Version/Release:
v4.4.1
Kubernetes Version [command: kubectl version]:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde

**Comment by J12934** [comment]
Hi @Alon-Katz 

Not 100% sure but this might be a helm / crd upgrade issue.
Helm install installs the CRD of the chart but helm upgrade does not upgrade it on changes.

We normally have a seperate head up warning about having to manually update the CRDs when the release had CRDs changes, but I forgot to add it to the 4.4.0 release.

So the CRD changes are in the release but not yet in your cluster so kubernetes doesn't allow you to use it yet.

I've updated the description of the release to now contain this notice, see:

https://github.com/secureCodeBox/secureCodeBox/releases/tag/v4.4.0

```bash
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/cascading.securecodebox.io_cascadingrules.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_clusterparsedefinitions.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_clusterscancompletionhooks.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_clusterscantypes.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_parsedefinitions.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_scancompletionhooks.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_scans.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_scantypes.yaml	
kubectl apply -f https://raw.githubusercontent.com/secureCodeBox/secureCodeBox/v4.4.0/operator/crds/execution.securecodebox.io_scheduledscans.yaml
```

**Comment by Alon-Katz** [comment]
Hi @J12934 , I tested this on a new Minikube instance with a fresh installation of SecureCodeBox v4.4.1, and I also tried to apply the CRD you provided, but the issue persists.

**Comment by Alon-Katz** [comment]
Hi @J12934 , Thanks for the quick release!
Seems like there is still an error, tried both with --set and with a values.yaml file (New minikube instance with a fresh install of v4.5.0 and also ran the crds apply just in case)

This is the set command: 
`helm upgrade --install new-scanner secureCodeBox/gitleaks --set parser.nodeSelector."beta\\.kubernetes\\.io/os"=linux -n securecodebox-system`

This is the same in values.yaml file:
```
parser:
    nodeSelector:
        beta.kubernetes.io/os: linux
```

Same result in both methods

```
W0317 19:07:37.250238   40628 warnings.go:70] unknown field "spec.nodeSelector.beta.kubernetes.io/os"
Error: UPGRADE FAILED: failed to create resource: ParseDefinition.execution.securecodebox.io "gitleaks-json" is invalid: spec.nodeSelector.nodeSelectorTerms: Required value
```

**Comment by J12934** [comment]
Hi @Alon-Katz 
sorry for the super long delay.
HAd a look now and found out whats wrong. 
The type pulled in the crd was wrong and therefore wasn't properly working unfortunatly. 

I've created a fix for it now and was able to test it with your helm install/upgrade command.
Should be working properly in the next release :)
