### ISSUE TITLE
Scans are marked as Failed after the First Jobs has failed

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#238]
## Current Status

The secureCodeBox Operator marks Scans as "Failed" if the job fails, even when the job gets restarted by Kubernetes and succeeds later.

## Expected Behavior

The scan is only marked as "Failed" if the retry limit for the job has been exceeded.

**Comment by Weltraumschaf** [comment]
This has a merged PR. Is it still valid?

**Comment by J12934** [comment]
@Weltraumschaf yes still valid.
I think the linked Pr was linked primary linked as they are somewhat related but merging it does not affect this issue.
