### ISSUE TITLE
Automatic Tweet on Release

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#245]
There's already something we can reuse: https://github.com/mugi111/tweet-trigger-release

**Comment by rseedorff** [comment]
Could be another improvement to post a message to slack also https://github.com/marketplace/actions/slack-notify

**Comment by twwd** [comment]
@rseedorff The GitHub Bot in Slack notifies already about release thus we have no need to include this in our workflow here.
