### ISSUE TITLE
DEFECTDOJO and MINIO ISSUE WITH CERTIFCATE 

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2501]
### Describe the bug
 We can't export report to defectdojo  due to Downloading Scan Result issue" 

### Steps To Reproduce

1. Run the scan (eg. nmap)  --> ok
2. Parse the result to MINIO --> ok
3. Export to defectodo --> KO

2024-05-30 09:01:07 INFO  DefectDojoPersistenceProvider:36 - Starting DefectDojo persistence provider
2024-05-30 09:01:15 INFO  DefectDojoPersistenceProvider:42 - Downloading Scan Result
2024-05-30 09:01:17 ERROR DefectDojoPersistenceProvider:30 - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:578)
    at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
    at io.securecodebox.persistence.service.S3Service.downloadFile(S3Service.java:43)

### Expected behavior
get report from minio bucket and push to defectdojo

### System (please complete the following information):

 - secureCodeBox 4.5.0
 - OS: Ubuntu 22.04
 - Kubernetes Version [1.28`]
 - Docker Version [command: `docker -v`]

### Screenshots / Logs
URL to get the report is the same regarding the parser and the ca provide to the pod is the same also.

Volumes:
  ca-certificate:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      securecodebox-s3-tls
    Optional:  false

**Comment by J12934** [comment]
Hi. 👋

The custom cert management for the DefectDojo hook is slightly different because Java doesn't use the same parameters as the rest of the software world.

We have some notes on the required config here: https://www.securecodebox.io/docs/hooks/defectdojo#additional-chart-configurations

Let me know if that helps.

**Comment by kaz-33** [comment]
Thx Jannix, 
I didn't understand this point of java :(
 Do you have an example of configmap creation with keystool?
  The MINIO certificate was created by k8S.

**Comment by kaz-33** [comment]
Hi all,
I get this error, it seems trustStorePassword is missing, I don't see the parameter in the chart? https://www.securecodebox.io/docs/hooks/defectdojo/#additional-chart-configurations
thx for your help

**Comment by kaz-33** [comment]
not so easy, but finally i's work fine.

**Comment by dyadek** [comment]
@kaz-33 could you please share how you resolve it?

**Comment by kaz-33** [comment]
@dyadek Sorry for the delay, I've been away for 2.5 months. It's a bit tricky because the pod "DefectDojo hook" is developped in java, you need  to push the certificate into the keystore with the keytool tool. I created a specific pod (java pod) to create a configuration map used by the pod DefectDojo hook.
