### ISSUE TITLE
zap-advanced: disable spider for API scanning

### ISSUE THREAD

**Issue by hamza86** [secureCodeBox/secureCodeBox#2508]
Hello guys, 

I'm trying to integrate zap with secureboxcode (using zap-advanced) within our CD to test pentest our Rest API using using openapi zap feature. Looking at the default configuraiton of zap-advanced, it looks like that there is no way to disable spider which is not appropriate for rest API. Is there any way to disable for example scanner default configuration, spider default configuration etc.. ? 
thanks in advance, 
Hamza

**Comment by J12934** [comment]
Hi no that's currently not supported AFAIK. It's always started but you can tune how long it runs to stop after a minute or so.

FYI (here too) zap advanced is going to deprecated soon. Recommendation is to start adopting Zap Automation Framework as soon as possible. See PR #2387

Will close this as not planned as we won't change it as it possible with the automation framework.
