### ISSUE TITLE
Typo3Scan is in public archive and no longer maintained

### ISSUE THREAD

**Issue by vo55** [secureCodeBox/secureCodeBox#2561]
It's rather an FYI - the implemented typo3scan is no longer maintained by the developer and should be considered to deprecate it in SCB as well?
 
https://github.com/whoot/Typo3Scan

**Comment by Weltraumschaf** [comment]
@vo55 Thanks for info.

**Comment by Weltraumschaf** [comment]
We deprecate Typo3Scan for version 4.x and remove it in 5.0.
