### ISSUE TITLE
403: denied: denied for oci repository 

### ISSUE THREAD

**Issue by Miker91** [secureCodeBox/secureCodeBox#2574]
### Steps To Reproduce
`helm --namespace securecodebox-system upgrade --install --create-namespace securecodebox-operator oci://ghcr.io/securecodebox/helm/operator`

### Screenshots / Logs
```
helm --namespace securecodebox-system upgrade --install --create-namespace securecodebox-operator oci://ghcr.io/securecodebox/helm/operator
Release "securecodebox-operator" does not exist. Installing it now.
Error: GET "https://ghcr.io/v2/securecodebox/helm/operator/tags/list": GET "https://ghcr.io/token?scope=repository%3Asecurecodebox%2Fhelm%2Foperator%3Apull&service=ghcr.io": unexpected status code 403: denied: denied
```

**Comment by Ilyesbdlala** [comment]
You need to be logged using a PAT to be able to access the ghcr.io.  The PAT should have a `read:packages` access.

```shell
export GITHUB_USERNAME=<your-github-username>
export GITHUB_PAT=<your-personal-access-token>

helm registry login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_PAT
```

**Comment by Miker91** [comment]
Thanks, it worked. Maybe it would be beneficial to add this to the doc?

**Comment by Ilyesbdlala** [comment]
> Thanks, it worked. Maybe it would be beneficial to add this to the doc?

My bad, after a bit of discussion and testing, it seems it is possible to use the registry without logging in. 
I had the same issue as you. But it was because my credentials were outdated.
As you can see here, when I logged out, it still worked:
```shell
$ helm registry logout ghcr.io
Removing login credentials for ghcr.io
$ helm registry logout ghcr.io/securecodebox
Removing login credentials for ghcr.io/securecodebox
$ helm --namespace securecodebox-system upgrade --install --create-namespace securecodebox-operator oci://ghcr.io/securecodebox/helm/operator
Pulled: ghcr.io/securecodebox/helm/operator:4.6.0
Digest: sha256:045700938ecea5839aaf4f36069b958b9969f5eb8297b4dc392b66886a96825a
Release "securecodebox-operator" has been upgraded. Happy Helming!
NAME: securecodebox-operator
LAST DEPLOYED: Fri Jul 26 16:40:40 2024
NAMESPACE: securecodebox-system
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
secureCodeBox Operator Deployed 🚀
```

So AFAIK it works as follows:
Anonymous ✅
Logged in ✅
Logged in with wrong/outdated credentials ❌

So we'll add a note on this in the [troubleshooting](https://www.securecodebox.io/docs/getting-started/troubleshooting/) page.
