### ISSUE TITLE
OCI chart address for secureCodeBox 

### ISSUE THREAD

**Issue by lauhong28** [secureCodeBox/secureCodeBox#2593]
I need correct OCI address where i can put for my helm-chart download. 

Hitting below errors by using https://charts.securecodebox.io as repo. 
..Unable to get an update from the "[https://charts.securecodebox.io/"](https://charts.securecodebox.io/%22) chart repository:
failed to fetch https://charts.securecodebox.io/index.yaml : 503 Service Unavailable

Reading the Blog, it has been migrated to OCI. May i have the OCI full address for helm chart to deploy. 

Downloading zap from repo oci://ghcr.io/securecodebox/helm/zap-automation-framework:4.7.0-alpha.1
Save error occurred:  could not download oci://ghcr.io/securecodebox/helm/zap-automation-framework:4.7.0-alpha.1/zap: invalid_reference: invalid tag

Please advise the repository address should use. 

dependencies:
- name: secureCodeBox
  alias: secureCodeBox
  version: 4.7.0-alpha.1
  repository: https://charts.securecodebox.io/

**Comment by Weltraumschaf** [comment]
Hi @lauhong28,

thanks for submitting this issue. We'll investigate this.

**Comment by Ilyesbdlala** [comment]
Hello :)
Running the following would install the latest supported zap-automation-framework version (which is currently `4.6.0` `4.7.0-alpha.1` is not recommended) using the CLI :
```shell
helm upgrade --install zap-automation-framework oci://ghcr.io/securecodebox/helm/zap-automation-framework --version 4.6.0
```

 As documented in https://helm.sh/docs/topics/registries/#specifying-dependencies. The name of the dependency is appended to the URL. So in Helm chart format it would be as follows.
 
 ```yaml
 dependencies:
  - name: zap-automation-framework
    version: 4.6.0
    repository: "oci://ghcr.io/securecodebox/helm"
 ```
