### ISSUE TITLE
Unable to see ZAP-Automation-Framework Scan Job trigger from ArgoCD UI 

### ISSUE THREAD

**Issue by lauhong28** [secureCodeBox/secureCodeBox#2618]
i have deployed zap automation framework via argoCD. i can see scantype was synced. I've edited values.yaml to include volume mount for the configmap of spiderjob.   I need advise how i can trigger this via argoCD or any configuration i need to change. Thank you. 

![Capture](https://github.com/user-attachments/assets/90ead05e-c468-4998-b00a-6c29f33f5631)
![zap-automation-framework](https://github.com/user-attachments/assets/47680ca0-b733-48d9-a7fb-6355cca456a0)
![Capture1](https://github.com/user-attachments/assets/1f07f2c2-8f4b-44af-992c-3837c9599a43)

**Comment by J12934** [comment]
HI @lauhong28 

You have only installed the "ScanType" you haven't created a scan yet.

The Scans are a seperate custom resource which use a Scan Type.
You can manage the Scans like any other Kubernetes resource in ArgoCD.

More on how scans and scan types work in the docs: https://www.securecodebox.io/docs/getting-started/first-scans
