### ISSUE TITLE
Using MS Teams as notification channel with new Workflows results in 400 Bad Request

### ISSUE THREAD

**Issue by Reduxx** [secureCodeBox/secureCodeBox#2664]
### Describe the bug
When trying to use MS Teams as a notification channel with the new Workflow Webhooks, which are [replacing the old Incoming Webhooks](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/), the job runs into 400 Bad Request.

### Steps To Reproduce
1. Create a new Workflow in MS Teams where the Trigger is "When a Teams webhook request is received"
2. Use "HTTP POST URL" as endPoint for ms-teams Notification WebHook
3. Run any scan (I ran the default nmap scan)

### Expected behavior
Normally the endpoint returns a 202 Accepted in case of the Workflows

### System:
 - secureCodeBox Version/Release
 - OS: MacOS 15.0
 - Kubernetes Server Version: v1.30.2 (Using kubernetes from Docker Desktop)
 - Docker Version: 27.2.0, build 3ab4256

### Screenshots / Logs
[nmap.log](https://github.com/user-attachments/files/17041756/nmap.log)

### Additional context
From what I gathered the client request from axios has the header "Content-Type: application/x-www-form-urlencoded" and when I do a curl request with that I also get a 400. If I change it in the curl request to "Content-Type: application/json" the webhook is triggered correctly and the message card appears in the channel as expected.

**Comment by J12934** [comment]
Ah thanks for reporting this, and looking into it already 🙌
Was also trying to setup / debug this last week, will try to get this fixed in the next release
