### ISSUE TITLE
Dedicated User For Parser Images

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#287]
I noticed that there are still some Docker Images that don't have a dedicated user.

Affected Parser Images:
- [ ] amass
- [ ] angular-csti-scanner
- [ ] gitleaks
- [ ] git-repo-scanner
- [ ] kubeaudit
- [ ] kube-hunter
- [ ] ncrack
- [ ] nikto
- [ ] nmap
- [ ] screenshooter
- [ ] ssh_scan
- [ ] sslyze test-scan
- [ ] trivy
- [ ] wpscan
- [ ] zap

See #285

**Comment by J12934** [comment]
All parsers have a non root user, that configured in the parser sdk image:
https://github.com/secureCodeBox/secureCodeBox/blob/main/parser-sdk/nodejs/Dockerfile#L12
