### ISSUE TITLE
List With Failing CI/CD Issues

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#295]
As developer of the *secureCodeBox* I need a stable CI/CD pipeline to develop properly.
To keep the CI/CD pipeline as stable as possible we should create a list documenting instabilities of CI/CD Jobs/Tests.

This list should contain:
- [ ] Failing Job
- [ ] Reason for Failure
- [ ] Date of Falure 
- [ ] Number of times failed per Job

See #362

**Comment by rseedorff** [comment]
Hi @fuhrmeistery, i guess we can close this issue since we are re-implementing the CI/CD process. What do you think?
