### ISSUE TITLE
🤖 Track new Scanner Version Releases 

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#304]
As developers of the securecCodeBox we want to release new scanner versions more frequently.
To enable us to update more frequently we need some kind of notification for the new scanner version.

One possible solution could be that GitHub provides Atom feeds for releases of repositories.
See: https://www.ronaldsvilcins.com/2020/03/26/rss-feeds-for-your-github-releases-tags-and-activity/
A Problem with this is that not all scanners provide releases on GH (e.g. nmap)

**Comment by rseedorff** [comment]
Thats a great idea! Maybe one can implement a new GitHub action for this task which periodicaly checks for new Versions based on their release pages or website an creates new Issues or even PRs like a Bot. 

Here is an example as a starting point how this could look like: https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release

We could give it name like "SCB Bot 🤖" 🙇🏻‍♂️

**Comment by rseedorff** [comment]
Could be implemented with #510
