### ISSUE TITLE
🚓  Integrate new XSS Scanner Dalfox

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#323]
## New Scanner implementation request

**Is your feature request related to a problem? Please describe.**
As User of the secureCodeBox I would like to use [Dalfox](https://github.com/hahwul/dalfox) to scan for XSS in my applications.

**Describe the solution you'd like**
Dalfox is integrated in the secureCodeBox

**Describe alternatives you've considered**
none

**Additional context**
Dalfox operates on a defined list of URLs. For auto-discovery a spider could be very useful

## Steps to implement a new scanner
Hint: A general guide how to implement a new SCB scanner is documented [here](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner).

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox/tree/master/scanners)
- [ ] Add a `README.gotmpl` and give a [brief overview](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/readme) of the scanner and its configuration options.
- [ ] Add a HelmChart and document all configuration options.
- [ ] Implement a new scanner specific `scan-type.yaml`
- [ ] Implement a new scanner specific `parse-definition.yaml`
- [ ] Add (optional) some `cascading-rules.yaml` like documented [here](https://docs.securecodebox.io/docs/api/crds/cascading-rule)
- [ ] Add (optional) a `Dockerfile` for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage
- [ ] Add some example `scan.yaml` and `finding.yaml` files in the [example folder](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/examples-dir)
- [ ] Implement a [new integration or E2E test](https://docs.securecodebox.io/docs/contributing/integrating-a-scanner/integration-tests) for the hook [here](https://github.com/secureCodeBox/secureCodeBox/tree/master/tests/integration)

**Comment by Weltraumschaf** [comment]
We do not plan to integrate this scanner at the moment. If there is more need from the community for this scanner please leave a comment here.
