### ISSUE TITLE
📚 Decide and Document a longterm support strategy

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#328]
As user and developer of the secureCodeBox I would like know the support strategy for this project.
This strategy should include:
- the number of versions currently supported
- EOL date for each version

At this Point there is no offical support timeline for a release.
We currently release about every two weeks dropping support for the previous version.

The strategy will be published in the GitHub repository as well as in the documentation of the secureCodeBox

**Comment by rseedorff** [comment]
This aspect also relates to the projects branching model. Here are some thoughts on that:
* theoretical background: https://martinfowler.com/articles/branching-patterns.html#mainline-integration
* example of a good project documentation: https://github.com/mobify/branching-strategy/blob/master/release-deployment.md

We should aim a solution which could be automated as much as possible based on GitHub Actions.
