### ISSUE TITLE
harmonize with other projects

### ISSUE THREAD

**Issue by javabeanz** [secureCodeBox/secureCodeBox#33]
OWASP Glue
DevSecOps Studio
https://www.owasp.org/index.php/OWASP_DevSecOps_Studio_Project

maybe there arre others. Saves perhaps lots of effort and energy !

**Comment by SebieF** [comment]
Page cannot be found - think we outlived them..

**Comment by J12934** [comment]
@SebieF might just be because of the OWASP Wiki move.
The glue repo is here: https://github.com/owasp/glue thought it doesn't seem to active.

**Comment by J12934** [comment]
Will close the issue for now, we're always happy to integrate and work together with other projects.
We also starting to work on integrating the secureCodeBox v2 with DefectDojo again.
