### ISSUE TITLE
Error: failed post-install: timed out waiting for the condition

### ISSUE THREAD

**Issue by JulienGuay** [secureCodeBox/secureCodeBox#335]
### Describe the bug
apiextensions.k8s.io/v1beta1 is Deprecated in v1.16 and planned for removal in v1.19. Use apiextensions.k8s.io/v1 CustomResourceDefinition instead.

rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole

### Steps To Reproduce
```
:~# helm repo add secureCodeBox https://charts.securecodebox.io
"secureCodeBox" has been added to your repositories
:~# helm --namespace securecodebox-system upgrade --install securecodebox-operator secureCodeBox/operator
Release "securecodebox-operator" does not exist. Installing it now.
W0322 08:14:15.403097  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:15.445106  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:15.487708  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:15.517242  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:15.610912  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:15.666557  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.695082  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.715874  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.733515  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.751753  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.792751  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:17.827889  374334 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 08:14:18.139354  374334 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0322 08:14:18.334909  374334 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Error: failed post-install: timed out waiting for the condition
```

### Expected behavior
installation should proceed without error with the latest API

### System (please complete the following information):
```
Ubuntu Focal Fossa 20.04.2 LTS
:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
:~# kind version
kind v0.10.0 go1.15.7 linux/amd64
:~# helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

### Screenshots / Logs
request specific commands and I will provide the resulting file.

### Additional context
I can safely downgrade the kind image server to an older version.

**Comment by rseedorff** [comment]
Hi @JulienGuay,

thx for reporting this issue 👍🏻. 

The warnings are related to issue #196 but shouldn't be a hard problem in K8S v1.20 in my opinion.

Regarding: `Error: failed post-install: timed out waiting for the condition`
- Is this problem reproducible? 
- Have you checked the resources (CPU, RAM) of you K8S Cluster? 
   - Is the timeout maybe somehow related to a ressource problem?

**Comment by J12934** [comment]
Also the output of `kubectl get pods -n securecodebox-system` and the logs of potentially failing pods would be helpful to debug this.

**Comment by JulienGuay** [comment]
NAME                                                 READY   STATUS             RESTARTS   AGE
securecodebox-controller-manager-544ccf7f49-wzrtm    0/1     ImagePullBackOff   0          86m
securecodebox-operator-minio-7db977dc57-bh2mf        0/1     ImagePullBackOff   0          86m
securecodebox-operator-minio-make-bucket-job-5zjlb   0/1     ImagePullBackOff   0          86m

**Comment by J12934** [comment]
Looks like your cluster is having problems to pull the images from the internet (docker hub).

Just to be save that it is pulling the correct image tags, can you check what image the operator (controller-manager) is using?

```bash
kubectl -n securecodebox-system get deployments.apps securecodebox-controller-manager -o yaml
```

Should be `docker.io/securecodebox/operator:2.5.2`

**Comment by JulienGuay** [comment]
That wouldn't suprise me we have a forced cloud proxy setup which may interfere with the pulling, but if I remeber my docker setup is set to pull from our artifactory server which then fetch it for me.

_helm --namespace securecodebox-system upgrade --install securecodebox-operator secureCodeBox/operator --debug
history.go:56: [debug] getting history for release securecodebox-operator
upgrade.go:123: [debug] preparing upgrade for securecodebox-operator
upgrade.go:131: [debug] performing update for securecodebox-operator
upgrade.go:303: [debug] creating upgraded release for securecodebox-operator
client.go:201: [debug] checking 27 resources for changes
client.go:464: [debug] Looks like there are no changes for ServiceAccount "securecodebox-operator-minio-update-prometheus-secret"
client.go:464: [debug] Looks like there are no changes for ServiceAccount "securecodebox-operator-minio"
client.go:464: [debug] Looks like there are no changes for ServiceAccount "securecodebox-operator"
client.go:464: [debug] Looks like there are no changes for Secret "securecodebox-operator-minio"
client.go:464: [debug] Looks like there are no changes for ConfigMap "securecodebox-operator-minio"
client.go:464: [debug] Looks like there are no changes for PersistentVolumeClaim "securecodebox-operator-minio"
W0322 09:50:10.406597  390217 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0322 09:50:10.408849  390217 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
client.go:464: [debug] Looks like there are no changes for ClusterRole "metrics-reader"
W0322 09:50:10.412266  390217 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
client.go:464: [debug] Looks like there are no changes for ClusterRole "proxy-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "parsedefinition-editor-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "parsedefinition-viewer-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scan-editor-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scan-viewer-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scantype-editor-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scantype-viewer-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scheduledscan-editor-role"
client.go:464: [debug] Looks like there are no changes for ClusterRole "scheduledscan-viewer-role"
client.go:464: [debug] Looks like there are no changes for ClusterRoleBinding "proxy-rolebinding"
client.go:464: [debug] Looks like there are no changes for ClusterRoleBinding "manager-rolebinding"
client.go:464: [debug] Looks like there are no changes for Role "securecodebox-operator-minio-update-prometheus-secret"
client.go:464: [debug] Looks like there are no changes for Role "leader-election-role"
client.go:464: [debug] Looks like there are no changes for RoleBinding "securecodebox-operator-minio-update-prometheus-secret"
client.go:464: [debug] Looks like there are no changes for RoleBinding "leader-election-rolebinding"
client.go:464: [debug] Looks like there are no changes for Service "securecodebox-operator-minio"
client.go:464: [debug] Looks like there are no changes for Service "controller-manager-metrics-service"
client.go:464: [debug] Looks like there are no changes for Deployment "securecodebox-operator-minio"
client.go:464: [debug] Looks like there are no changes for Deployment "securecodebox-controller-manager"
client.go:282: [debug] Starting delete for "securecodebox-operator-minio-make-bucket-job" Job
client.go:122: [debug] creating 1 resource(s)
client.go:491: [debug] Watching for changes to Job securecodebox-operator-minio-make-bucket-job with timeout of 5m0s
client.go:519: [debug] Add/Modify event for securecodebox-operator-minio-make-bucket-job: ADDED
client.go:558: [debug] securecodebox-operator-minio-make-bucket-job: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for securecodebox-operator-minio-make-bucket-job: MODIFIED
client.go:558: [debug] securecodebox-operator-minio-make-bucket-job: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:369: [debug] warning: Upgrade "securecodebox-operator" failed: post-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
helm.go:81: [debug] post-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374_

#kubectl output attached in .txt file
[output.txt](https://github.com/secureCodeBox/secureCodeBox/files/6182714/output.txt)
