### ISSUE TITLE
persistence-defectdojo helm install fails

### ISSUE THREAD

**Issue by hmadej** [secureCodeBox/secureCodeBox#355]
### Describe the bug

when following the install instructions for the hook for defect dojo I get this error:

helm upgrade --install dd secureCodeBox/persistence-defectdojo \
    --set="defectdojo.url=https://defectdojo-django.default.svc"

Error: failed to download "secureCodeBox/persistence-defectdojo" (hint: running `helm repo update` may help)

I have run `helm repo update`, it produces the same error after updating

### Steps To Reproduce
helm upgrade --install dd secureCodeBox/persistence-defectdojo \
    --set="defectdojo.url=https://defectdojo-django.default.svc"

### Expected behavior
able to download and install the hook

**Comment by rseedorff** [comment]
Hi @hmadej,

thx for reporting this issue 🤗 Our current release is [v2.5.2](https://github.com/secureCodeBox/secureCodeBox/releases/tag/v2.5.2) and you find all secureCodeBox HelmChart artifacts at [artifactHub.io](https://artifacthub.io/packages/search?page=1&org=securecodebox).

Our [Documentation](https://docs.securecodebox.io/docs/hooks/defectdojo) or [GH Source](https://github.com/secureCodeBox/secureCodeBox/tree/main/hooks/persistence-defectdojo) is a little bit feature driven and contains already features we haven't released for now 🙄.  This seems to be a bug in our documentation build process 🤔

The new secureCodeBox DefectDojo integration will be part of our next minor release v2.6.0 🎉 and will be then easily installable via the referenced helm chart. As for now we haven't released all the DefectDojo stuff.

Our Team plans to release the next release v2.6.0 at the end of the current week (friday).  If you want to try our DefectDojo integration before that please try to check out our `main` branch and install the DefectDojo Hook based on that branch. 

For example:

```bash
git clone https://github.com/secureCodeBox/secureCodeBox.git
cd secureCodeBox
helm upgrade --install dd ./hooks/persistence-defectdojo
--set="defectdojo.url=https://defectdojo-django.default.svc"
```

**Comment by hmadej** [comment]
Hi @rseedorff,

That worked! Now I am seeing an issue with pulling the image:

Failed to pull image "docker.io/securecodebox/persistence-defectdojo:v2.6.0-alpha1": rpc error: code = Unknown desc = Error response from daemon: manifest for securecodebox/persistence-defectdojo:v2.6.0-alpha1 not found: manifest unknown: manifest unknown

**Comment by J12934** [comment]
@hmadej mh yeah this is still pulling a unreleased image.

You can overwrite this to use the image build automatically from the main branch:

```bash
helm upgrade --install dd ./hooks/persistence-defectdojo --set="defectdojo.url=https://defectdojo-django.default.svc" --set="image.tag=main"
```

**Comment by hmadej** [comment]
awesome, got it up and running, and works great so far!

**Comment by rseedorff** [comment]
Closing this now. Please get in touch if you have any further issues or questions.
