### ISSUE TITLE
Improve the GitHub CI Workflow support Fork PRs

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#362]
### Is your feature request related to a problem?

As secureCobeBox maintainer i would like to review PRs based on contributer forks with the project ci and all checks.

### Describe the solution you'd like

- Working with forks gets easier for contributors (less secrets/services to configure)
- Working with forks gets easier for maintainers (enable the maintainer to see if CI is passing on a fork)
- Increase stability
	- Fewer failures caused by flaky connections to DockerHub
	- Fewer failures caused by flaky timeouts (See #224 )
- Keep CI execution time to a minimum

### Additional context

- https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions
- https://github.com/marketplace/actions/build-and-publish-docker-image-to-github-packages-registry
- Docker Image Layer Caching: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
- Share Secrets to Forks: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
  - Possible security Issues: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- Using a local registry: https://stackoverflow.com/questions/63887031/build-docker-image-locally-in-github-actions-using-docker-build-push-action
  - Export Docker Images: https://docs.docker.com/engine/reference/commandline/export/. https://docs.docker.com/engine/reference/commandline/save/
  - KIND Import Docker Images: https://kind.sigs.k8s.io/docs/user/quick-start#loading-an-image-into-your-cluster
- https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

See #476

**Comment by J12934** [comment]
This has been resolved for a while now :)
