### ISSUE TITLE
❄️  Bugfix Flaky Unit Tests For JavaScript Subprojects

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#364]
## 🐞 Bug report

Developing some new Hooks we noticed some strange behavior between independet JS Subprojects when we executed our unit tests with jest.
It seems that mocking modules in different subprojects causes some tests to fail when executed together although they are independent and there mocks should be seperate.

Until now we are not quite sure why this happens. We think it could be a problem related to es/commonJS modules

**Comment by twwd** [comment]
Ich würde vermuten, dass die Tests nicht unabhängig ausgeführt werden. Jest gibt auch eine entsprechende Warnung über die doppelten Mocks.
```
jest-haste-map: duplicate manual mock found: axios
  The following files share their name; please delete one of them:
    * <rootDir>/generic-webhook/__mocks__/axios.js
    * <rootDir>/teams-webhook/__mocks__/axios.js

jest-haste-map: duplicate manual mock found: axios
  The following files share their name; please delete one of them:
    * <rootDir>/hooks/generic-webhook/__mocks__/axios.js
    * <rootDir>/hooks/teams-webhook/__mocks__/axios.js
```

**Comment by twwd** [comment]
Also see https://github.com/facebook/jest/issues/2070

**Comment by fuhrmeistery** [comment]
That is correct but on this branch https://github.com/fuhrmeistery/secureCodeBox/tree/feature/notification-hook
We removed both  custom mock implementations completely and use jest.mock() instead and the issue still persisted

> I would guess that the tests are not executed independently. Jest also gives an appropriate warning about the duplicate mocks.
> 
> ```
> jest-haste-map: duplicate manual mock found: axios
>   The following files share their name; please delete one of them:
>     * <rootDir>/generic-webhook/__mocks__/axios.js
>     * <rootDir>/teams-webhook/__mocks__/axios.js
> 
> jest-haste-map: duplicate manual mock found: axios
>   The following files share their name; please delete one of them:
>     * <rootDir>/hooks/generic-webhook/__mocks__/axios.js
>     * <rootDir>/hooks/teams-webhook/__mocks__/axios.js
> ```
