### ISSUE TITLE
Unable to revive connection: http://persistence-elasticsearch:9200

### ISSUE THREAD

**Issue by pchan0o** [secureCodeBox/secureCodeBox#37]
Hi there,

I am getting the following error with the docker-compose up:

`persistence-kibana_1              | {"type":"log","@timestamp":"2018-07-05T12:44:52Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://persistence-elasticsearch:9200/"}`

My environment:
Ubuntu server 18.04 amd64
Docker version: 18.03.1-ce
Docker-compose version: 1.21.2

I also cannot ping http://persistence-elasticsearch:9200. 
Did the address to the elastic search change perhaps? 

Regards,

**Comment by Trosky** [comment]
Hi @pchan0o,
have you seen the FAQ at https://github.com/secureCodeBox/secureCodeBox#faq ?

> Elasticsearch container fails to start: "max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]"
> On the host machine run sysctl -w vm.max_map_count=262144 as root. To make the change persistent add the line vm.max_map_count=262144 to /etc/sysctl.conf.

Might be your problem ;)

**Comment by pchan0o** [comment]
Missed that.
Thanks :)
