### ISSUE TITLE
Include Kubernetes V1.21 To Integration Test Matrix

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#393]
As developer/user of the secureCodeBox I want to make sure that the latest version of Kubernetes is able to run the secureCodeBox project.

### Solution

Include Kubernetes v1.21 in the integration test matrix

**Comment by J12934** [comment]
Kind currently doesn't have 1.21 node images yet https://hub.docker.com/r/kindest/node/tags :(

They seem to be having some issues building them, should hopefully be out in a couple of weeks
