### ISSUE TITLE
secureCodeBox not initializing

### ISSUE THREAD

**Issue by jwmkrezmien** [secureCodeBox/secureCodeBox#40]
Dear secureCodeBox team,

I decide to spin your box, but unfortunately I do not seem to be able to initialize secureCodeBox in docker. When running docker ps -a, I noticed that securecodebox/engine:oss exited. References are provided in the log-files. Obviously, port 8080 is not hosting any web application (checked with netstat). Lastly, the log files seem to run in a loop while showing the following output.

scanner-webapplication-arachni_1  | D, [2018-08-06T12:21:25.710779 #7] DEBUG -- : Getting new scans
scanner-webapplication-arachni_1  | D, [2018-08-06T12:21:25.711148 #7] DEBUG -- : fetching task
scanner-webapplication-arachni_1  | D, [2018-08-06T12:21:25.722771 #7] DEBUG -- : Error while connecting to http://engine:8080/box/jobs/lock/arachni_webapplicationscan/ce6d88dc-13fb-4ef5-a801-c897fba09d87
scanner-webapplication-arachni_1  | D, [2018-08-06T12:21:25.723134 #7] DEBUG -- : Failed to open TCP connection to engine:8080 (getaddrinfo: Temporary failure in name resolution)
scanner-webapplication-arachni_1  | D, [2018-08-06T12:21:25.723446 #7] DEBUG -- : Sleeping for 5...

We have checked the script both in a Ubuntu 18.04 box on VMWare and a Ubuntu 16.04 box on AWS.  In both instances, we have updated the virtual memory (MAX MAP COUNT variable). Both seem to run into the same problems.

Any suggestions?

KR, JK

**Comment by rseedorff** [comment]
Hi JK,

thanks for your interest! Can you please help us and provide some log informations regarding the **securecodebox/engine:oss** container, e.g. with `docker logs securecodebox_engine_1`.

The output you already provided is the consequence of the exited engine container, but can not explain the reason. Maybe its a virtual memory (RAM) issue?

KR, Robert

**Comment by jwmkrezmien** [comment]
Hi Robert,

Attached the requested logs.

KR, JK

[secureCodeBox_engine.log](https://github.com/secureCodeBox/secureCodeBox/files/2263869/secureCodeBox_engine.log)

**Comment by J12934** [comment]
Hi 👋
It looks like your engine container cannot start properly because it cannot connect to the mysql server.
```
Cannot create PoolableConnectionFactory (null,  message from server: "Host '172.18.0.5' is not allowed to connect to this MySQL server")
```

Did you start the complete docker-compose, including the camundadb or did you use an external database instance?

**Comment by jwmkrezmien** [comment]
Hi,

I ran the instructions as provided on: https://github.com/secureCodeBox/secureCodeBox. So regular docker-compose up with the default .env settings. No external database was configured (on the VMWare environment the host has MySQL installed, in the AWS environment this was not the case). To me this bit of the documentation is unclear. I see that a MySQL container is downloaded by default, guessing that it will use that container. Or is it somehow using the host's MySQL server?

KR, JK

**Comment by J12934** [comment]
Mhh, yes it should use the mysql container it started with the docker-compose.
Can you verify that the mysql container is actually running? (Should be called something like `securecodebox_camundadb_1`)

**Comment by jwmkrezmien** [comment]
root@ubuntu:~# docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS                                            NAMES
286c9193bdd6        rabbitmq:3                                            "docker-entrypoint.s…"   8 hours ago         Exited (0) 8 hours ago                                                       vibrant_shirley
10e0ac4deaf3        rabbitmq:3                                            "docker-entrypoint.s…"   8 hours ago         Exited (0) 8 hours ago                                                       nervous_kilby
bbdc5ab01c11        securecodebox/nikto:oss                               "ruby /sectools/src/…"   32 hours ago        Up 4 minutes                8080/tcp                                         securecodebox_scanner-webserver-nikto_1
26236a9c40f6        securecodebox/zap:oss                                 "/home/zap/init.sh"      32 hours ago        Up 4 minutes (healthy)      8080/tcp, 8090/tcp                               securecodebox_scanner-webapplication-zap_1
58a075539d6a        securecodebox/sslyze:oss                              "npm start"              32 hours ago        Up 4 minutes                8080/tcp                                         securecodebox_scanner-webapplication-sslyze_1
2f873b303221        securecodebox/arachni:oss                             "bash /sectools/src/…"   32 hours ago        Up 4 minutes                8080/tcp                                         securecodebox_scanner-webapplication-arachni_1
1e887f96f320        securecodebox/nmap:oss                                "npm start"              32 hours ago        Up 4 minutes                8080/tcp                                         securecodebox_scanner-infrastructure-nmap_1
861828a1e95b        securecodebox/engine:oss                              "java -Dloader.path=…"   32 hours ago        Exited (1) 32 seconds ago                                                    securecodebox_engine_1
980f06715439        docker.elastic.co/kibana/kibana:6.2.3                 "/bin/bash /usr/loca…"   32 hours ago        Up 4 minutes                0.0.0.0:5601->5601/tcp                           securecodebox_persistence-kibana_1
d90ef8c29b19        docker.elastic.co/elasticsearch/elasticsearch:6.2.3   "/usr/local/bin/dock…"   32 hours ago        Up 4 minutes                0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   securecodebox_persistence-elasticsearch_1
d10cd2217cb1        mysql:5.7                                             "docker-entrypoint.s…"   32 hours ago        Up 4 minutes                3306/tcp                                         securecodebox_camundadb_1

**Comment by Trosky** [comment]
@J12934 @rseedorff The Exception of the engine indicates that the ip of the engine docker container is not allowed to connect to the mysql container. 

I'm not sure how the default mysql container configures it's grants.

**Comment by Trosky** [comment]
@jwmkrezmien can you please give us the following informations:
* `docker -v`
* `docker-compose -v`
* `docker network inspect securecodebox_frontend`

**Please be aware that the full output of the following commands contains secrets. Please review the output!** 

For us from interest are the HostConfig -> NetworkMode field and the NetworkSettings section.
* `docker container inspect securecodebox_camundadb_1` 
* `docker container securecodebox_engine_1`

**Comment by jwmkrezmien** [comment]
root@ubuntu:~# docker -v
Docker version 18.06.0-ce, build 0ffa825
root@ubuntu:~# docker-compose -v
docker-compose version 1.17.1, build unknown

[inspect_frontend.txt](https://github.com/secureCodeBox/secureCodeBox/files/2271712/inspect_frontend.txt)
[inspect_camundadb_1.txt](https://github.com/secureCodeBox/secureCodeBox/files/2271713/inspect_camundadb_1.txt)
[inspect_engine.txt](https://github.com/secureCodeBox/secureCodeBox/files/2271714/inspect_engine.txt)

**Comment by jwmkrezmien** [comment]
Any update?

**Comment by J12934** [comment]
Hi
I'm not very skilled in reading reading and analyzing these kinds of logs, but they look pretty normal to me.

While browsing for possible causes for this issue i came across this [issue](https://github.com/docker-library/mysql/issues/275#issuecomment-292208567) which seems to be the exact problem. Can you try the suggested solutions? The easiest one seems to be to reset the volumes.

**Comment by Trosky** [comment]
The networking seems to be ok.

If the suggested reset of the volumes does not help. You can give mariadb a try:

- docker-compose down
- Delete the database volume
- replace in the compose file: `image: mysql:5.7 ` with `image: mariadb:10.2`
- Try it out: docker-compose up

More details: https://hub.docker.com/_/mariadb/

**Comment by rseedorff** [comment]
@jwmkrezmien Any update here? Have you tried it again?

**Comment by loket** [comment]
I have the same problem as @jwmkrezmien. Running on macOS High Sierra.

```bash
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
$ docker-compose -v
docker-compose version 1.22.0, build f46880f
```

I tried replacing `mysql:5.7` with `mariadb:10.2` (after stopping the containers and deleting the volumes), but the problem remains.

Any more hints? 😃

**Comment by Trosky** [comment]
It seems that other projects also have similar problems with the mysql docker containers. 

Some people had success by deleting the volume and the mysql image + base images. 

An other idea would be to remove the volume from the container to check if it's probably some kind of issue with the docker filesystem.

**Comment by SajidPervez** [comment]
Hi
I am trying to setup SCB on a Ubuntu VM and facing issues with initialization. I have tried a number of things from this thread but with out any success so far! I am attaching some logs here to see if anyone can point me where and what am I doing wrong. Thanks
[docker_ps_a.log](https://github.com/secureCodeBox/secureCodeBox/files/3279071/docker_ps_a.log)
[securecodebox_engine_1.log](https://github.com/secureCodeBox/secureCodeBox/files/3279075/securecodebox_engine_1.log)

[docker-compose.yml.txt](https://github.com/secureCodeBox/secureCodeBox/files/3279077/docker-compose.yml.txt)

**Comment by J12934** [comment]
Hi @SajidPervez 👋
thank you for the reports.
The engine looks more or less fine by itself, the problems seems to be with the containers the engine depends on, mainly the database (container: `camundadb`).

Also weird that all containers exited with the same code (255)...

Could you try to do a clean start of the stack?:

```bash
docker-compose stop
docker-compose rm

docker-compose up
```

**Comment by SajidPervez** [comment]
Hi Jannik,
Thanks a ton, It did work and now experimenting with it.

Regards,
Sajid Pervez.
