### ISSUE TITLE
Cannot save advanced scan parameters

### ISSUE THREAD

**Issue by gecz83** [secureCodeBox/secureCodeBox#41]
Hi, 
I installed scb via docker-compose, added a user, granted it all permissions and roles and spun up instances of dvwa and juice-shop to test on.
When I try to initiate an advanced scan I get a ticket and claim it, but when I try to set anything in the advanced parameters field (i.e. nmap -A localhost or nikto -host localhost -port 3000) the "Complete" Button is disabled, same goes for the "Save" button. I can click it once, but when I refresh the ticket no changes are actually saved. 
Is this a known bug or am I doing something wrong?

Thanks in advance, Cheers!

**Comment by J12934** [comment]
Hi 👋
Mhh can't reproduce the bug you are describing...

When i set up a scan using the advanced parameters the save button is disabled, but the complete button enabled and working as intended.

I attached a screenshot of the way it should look like. (I removed the command line options listing as it was getting in the way)
![image](https://user-images.githubusercontent.com/13718901/43767239-e14a5638-9a34-11e8-9135-bfeeab2f882c.png)

Are you sure that the task is assigned to your user account and the rights are ok? This is off the top of my head the first causes for such a behavior.

**Comment by J12934** [comment]
Also on the topic of nmap advanced parameters, especially the `-A` flag.
`-A` scans currently don't work properly as nmap needs to be run with administrator privileges. (This issue is tracked here: https://github.com/secureCodeBox/scanner-infrastructure-nmap/issues/2)
When using NSE you will likely also encounter problems. As this integration wasn't really tested so far.

**Comment by gecz83** [comment]
Okay, I started from scratch an now the advanced parameters get applied and I receive the "Review scan results" ticket. Thanks for the heads-up regarding nmap -A.
Cheers!

**Comment by gecz83** [comment]
Hi, 
unfortunately I just got the same behaviour again. I tried an advanced nmap scan and wanted to add 
-p 3000. The Complete Button was inactive again. 
Any ideas what could cause this?
Cheers! 
![nmap-advanced1](https://user-images.githubusercontent.com/41999055/44034579-bae5abd6-9f0d-11e8-9c16-06c23d999d5f.png)
![nmap-advanced2](https://user-images.githubusercontent.com/41999055/44034587-bfbef874-9f0d-11e8-8778-3652f4b5dc6a.png)

**Comment by J12934** [comment]
Hi again 😉
whats seems odd to me on these screenshots is that the target host is empty in the field.
Did you enter the Target host in the previous step? Normally that host should show up in the disabled form input field. (See my screenshot).

**Comment by Trosky** [comment]
Hi, 
can you try opening the Browser Developer Tools? Probably there is some kind of JavaScript-Error.

**Comment by gecz83** [comment]
I think I found it. 
When I initiate the scan with localhost:3000 the Target Host in the ticket is empty.
![nmap-advanced3](https://user-images.githubusercontent.com/41999055/44077612-846344d2-9fa4-11e8-808d-33f7e44a4e1e.png)

If I don't then Target Host gets populated with "localhost"
![nmap-advanced4](https://user-images.githubusercontent.com/41999055/44077858-3caa1a84-9fa5-11e8-916a-5cb13dbb36b7.png)

**Comment by gecz83** [comment]
Another strange thing... When I initiate an advanced scan and later adding the -p 3000 parameters I get an empty report 
![nmap-advanced5](https://user-images.githubusercontent.com/41999055/44078369-94e412ee-9fa6-11e8-8aba-6af7e928ad85.png)

But when I initiate a default scan with localhost:3000 I get the full report
![nmap-default2](https://user-images.githubusercontent.com/41999055/44078407-af800e00-9fa6-11e8-820d-96cfb4f9e659.png)

![nmap-default3](https://user-images.githubusercontent.com/41999055/44078418-b3bce45c-9fa6-11e8-948c-8d14b3700d03.png)

Any advice on this one?
Cheers!

**Comment by J12934** [comment]
`localhost:3000` doesn't seem to be a valid target for nmap.
At least when i run nmap directly with this as the target, it wont accept it.
```
➜ nmap localhost:3000
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-14 09:47 CEST
Failed to resolve "localhost:3000".
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.07 seconds
```

It's interesting that the scanner works regardless of the `:3000` in the target 😅

Looking at the report it also seems as if the scan with `-p 3000` seems to be correct as there seems to be no port 3000 open at your machine,

**Comment by gecz83** [comment]
Okay now it's getting strange =)
Port 3000 is definitely open because of Juice Shop. When I run the host version on nmap I get this output

> [gecz@dso-playground ~]$ nmap localhost  -p 3000
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-14 09:53 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000074s latency).
Other addresses for localhost (not scanned): ::1
PORT     STATE SERVICE
3000/tcp open  ppp
Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds

**Comment by J12934** [comment]
😅
I assume your are running the nmap scanner via docker, right?
If so `localhost` would be `localhost` of the docker container. Not of your host system.

**Comment by Trosky** [comment]
@J12934 maybe we should add some validation to the fields ?

@gecz83 This depends a little bit on how you operate Docker: 
The nmap container sits in a (virtual) docker network. So localhost will scan the nmap container itself. You either provide the juice shop hostname to the nmap container or your hostmachine ip address. (If you use something like docker for windows or docker-machine the host ip might be  different).

**Comment by gecz83** [comment]
@J12934 Whoops my bad. :sweat_smile: (I'm new to docker)
@Trosky Thanks for the advice, now it works!

**Comment by J12934** [comment]
@Trosky Hostname validation was already added in https://github.com/secureCodeBox/engine/pull/17.
This is issue is probably based on a older build.

**Comment by gecz83** [comment]
@J12934 Hhmm... strange. I deleted and pulled the images a week ago. Are there any configs / persistent storage locations I'm missing?

**Comment by J12934** [comment]
Mhh no that should have worked.
Will take a look at the validation maybe i missed something with the validation regex.

**Comment by J12934** [comment]
Okay there really was an error in the hostname validation in it validating the target name not the target location / hostname.
This gets fixed with https://github.com/secureCodeBox/engine/pull/25

**Comment by gecz83** [comment]
Hi,
I just tested the new images and can confirm it's working as expected. 
Thanks and Cheers!
