### ISSUE TITLE
New Scanner: Integrate a Wordpress Scanner

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#47]
**Is your feature request related to a problem?**
As an DevSecOps developer i want to use the [Wordpress Security Scanner](https://wpscan.org/) with the secureCodeBox, to test my Wordpress instance,  if there are some old plugin versions installed.

> Hint: If you are new and need some help implementing a new security for the secureCodeBox, please have a look at our [documentation]( https://github.com/secureCodeBox/secureCodeBox/tree/master/docs/developer-guide).

## Steps to implement a new scanner
A general guide how to implement a new scanner is documented [here]( https://github.com/secureCodeBox/secureCodeBox/blob/master/docs/developer-guide/README.md#developing-own-processes)

### Must have
- [x] Create a [new public secureCodeBox repository](https://github.com/organizations/secureCodeBox/repositories/new) for the scanner implementation
- [x] Implement a new scanner microservice an reuse some of the existing stuff, if possible
- [x] Check if there is a [healthcheck](https://github.com/secureCodeBox/secureCodeBox/blob/master/docs/developer-guide/README.md#healthchecks-for-scanner-microservices) for the microservice implemented
- [x] Implement a [new basic security process](https://github.com/secureCodeBox/secureCodeBox/blob/master/docs/developer-guide/README.md#developing-a-process-model) for the scanner
- [x] Update the [docker-compose](https://github.com/secureCodeBox/secureCodeBox/blob/master/docker-compose.yml) files and integrate your new scanner there
- [x] Update the [user guide](https://github.com/secureCodeBox/secureCodeBox/tree/master/docs/user-guide) and [developer guide](https://github.com/secureCodeBox/secureCodeBox/tree/master/docs/developer-guide)
- [x] Implement a integration test for the scanner [here](https://github.com/secureCodeBox/secureCodeBox/tree/master/test)

### Should have
- [ ] Update the [CLI examples](https://github.com/secureCodeBox/secureCodeBox/tree/master/cli)
- [ ] Update the [Jenkins Pipeline](https://github.com/secureCodeBox/integration-pipeline-jenkins-examples) examples
- [ ] Update the [OpenShift Container Setup](https://github.com/secureCodeBox/ansible-role-securecodebox-openshift)

**Comment by rseedorff** [comment]
I have added a new public repository for that: https://github.com/secureCodeBox/scanner-cms-wpscan

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate WPScan to public GitHub Repo (and adapt the new Engine API)](https://trello.com/c/7iR0AA9o/229-migrate-wpscan-to-public-github-repo-and-adapt-the-new-engine-api)

**Comment by rseedorff** [comment]
This issues could be combined with #77

**Comment by nzpopa** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Migrate WPScan to public GitHub Repo (and adapt the new Engine API)](https://trello.com/c/7iR0AA9o/229-migrate-wpscan-to-public-github-repo-and-adapt-the-new-engine-api)

Dead or not public :-) 
Can I get an invite?
I'd like to handle the wpscan integration.

**Comment by J12934** [comment]
Haha, yeah thats our internal trello board. We also track tasks related to using the secureCodeBox internally in our company, so unfortunately can't open it to the public :(

@dpatanin is already working on the integration. You can take a look at the scanner repo here: https://github.com/secureCodeBox/scanner-cms-wpscan/tree/develop

**Comment by rseedorff** [comment]
Hi @nzpopa 👋🏻
in between ;-) currently @dpatanin is working on it. You can see the development here: https://github.com/secureCodeBox/scanner-cms-wpscan/tree/develop

Open are the following tasks:
- [] Support more parameter options (scanner traget options which will be used to start wpscan) at the scanner side
- [] Implement a "finding transformation" -> translation of the WPScan results to generic SCB finding results

**Comment by dpatanin** [comment]
Hey @nzpopa :)
A quick update for you: 
Most part is already finished, meaning a working wrapper including some parameter options.
Sadly i cannot push it yet due to an permission issue linked to my acc. :(
I'm looking forward to get it fixed the next days.
