### ISSUE TITLE
Configuration Of An Email Notification

### ISSUE THREAD

**Issue by dpotapovich** [secureCodeBox/secureCodeBox#488]
Good day colleagues,

I read the topic from the documentation related to Notification Hook and did not quite figure out how to pass variables to _values.yaml_.  For example, I have credentials for connection local SMTP:
**port = 587
host = "mail.example.corp"
secure = "true"
username and password**

But we have only this string in values.yaml:
   **env:
      - name: SMTP_CONFIG
      value: "smtp://user@domain.tld:pass@smtp.domain.tld/"**

Please tell me how to correctly throw all the necessary parameters so that they are read correctly and letters are sent to the specified mailbox. Looking forward to your response.

**Comment by fuhrmeistery** [comment]
Thank you for your question.

In the email notifier, we are using nodemailer.
Nodemailer provides an option to provide all necessary information in a single connection string.
So we are handing this connection string from the values over to nodmailer to handle the request.
I think the string in our example is a little wrong good catch.

For you provided example the string should be `smtp://username:password@mail.example.corp/?secure=true`

For more details, I would recommend taking a look at the [Nodmailer Docs](https://nodemailer.com/smtp/).
They describe all the available options like changing ports, pooling and many more.

Does this help resolve your issue?

**Comment by dpotapovich** [comment]
Oh, thank you very much, it became clearer. Is it possible to choose the recipient of the letter at this link?

**Comment by dpotapovich** [comment]
@fuhrmeistery I found that the **email type** is still in development. Is true?
**The `type` specifies the type of the notification (in this example slack).
Currently `slack` is the only available type, but we are working on others (e.g. MS Teams or email) as well.**

**Comment by fuhrmeistery** [comment]
I don't think it is possible to add the recipient in the connection string.

In the values in your notificationChannel definition, you need to set the `endPoint` to the email you want to send you mail to.
I think I have to improve the documentation to be more clear at this point.

The email notifier is already released (2.7.0), but I forgot to remove this line in the docs.
