### ISSUE TITLE
➹ Implement a lightweight false-/positive-handling

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#49]
As a user I would like to have a lightweight false-/positive-handling which helps me to label/mark and filter findings which are not relevant or false-/positive.

I would like to file all findings in my security dashboard (kibana).

See #225

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EPIC: False / Positive Handling implementieren](https://trello.com/c/mQCS5axC/126-epic-false-positive-handling-implementieren)

**Comment by fuhrmeistery** [comment]
This depends on: PR #225

**Comment by fuhrmeistery** [comment]
As described in PR #225 we want to introduce a hash value to the finding model.
This hash has to be set/updated in the parser of the scanner as well as in each hook modifying findings.
To avoid duplication we should introduce a new `npm` package containing a  function to calculate the hash consistently. For this purpose I took a look at the parser-sdk and the hook-sdk and found at least one duplication (code for `uploadFile()`). This rose the question if we want to create a `scb-sdk` combining `parser-sdk` and `hook-sdk` as well as their helpers. 
Consequences would be some minor refactoring of hooks and parsers to use the `scb-sdk`

**Comment by J12934** [comment]
@fuhrmeistery great idea 👍
We might be able to avoid publishing to npm referencing the scb-sdk in the package.json via a file-path.
This would probably simplify this a bit.

**Comment by fuhrmeistery** [comment]
In PR #330 @J12934 suggests that the DefectDojo persistence provider is run as a ReadAndWrite Hook before other hooks are executed.
Similar to this we could add a simple hook that runs before every other hook to realise a lightweight false positive handling.

This Hook could be optional and would be replaced by a much more suffisticated alternative like DefectDojo.
This way we could introduce an immutable hash without having to worry about the execution order of ReadWriteHooks.

See [ADR 0007](https://github.com/secureCodeBox/secureCodeBox/blob/main/docs/adr/adr_0007.adoc)
See PR #330
