### ISSUE TITLE
Align Hook Directory Structure With Scanner

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#495]
I noticed that scanners and hooks use a different approach in their directory structure.
For the scanners there are subdirectories for `parser` and `scanner` (if existing) while the source code for the hook resides directly in its root directory.

I think we should introduce a `hook` directory inside each hook containing its source code to make their structure more clean.

**Comment by rseedorff** [comment]
Hi @fuhrmeistery,

thx for this issue, i totally agree with you :-)

I had the same idea and problem which came up implementing my documentation PR #475
