### ISSUE TITLE
Fix codeclimate code coverage calculation

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#505]
### Describe the bug

The codeclimate code coverage statistic seems to be broken somehow because there are files analyzed which don't exist 🤔.

As you can see here https://codeclimate.com/github/secureCodeBox/secureCodeBox/code?sort=test_coverage (order desc) the first two entries reference to files (with a bad rating: F) which don't even exist:
- https://codeclimate.com/github/secureCodeBox/secureCodeBox/hooks/declarative-subsequent-scans/scan-helpers.js
- https://codeclimate.com/github/secureCodeBox/secureCodeBox/hooks/declarative-subsequent-scans/hook.js

We already tried to exclude this files via exclusion rule here, but that doesn't help either: https://github.com/secureCodeBox/secureCodeBox/blob/625547e88052644458ee0d46c33ec65ace275fff/.codeclimate.yml#L51

Maybe this issue is introduced somewhere in the process of compiling typescript to javascript (CI Pipeline) but even though such generated javascript files must be ignored, because they are generated and we couldn't change that code.

### Expected behavior

The codeclimate code coverage metrics should only be based on valid existing code files, not generated code files.

**Comment by rseedorff** [comment]
Codeclimate Feedback on that:

> For context, coverage data for your repo is actually entirely based on the data that you send us via your coverage payload, which is created there in your CI. On the analysis side, however, your in-app (or .codeclimate.yml) exclusions do have an effect on the files we analyze, but not the test coverage that we report. 
> 
> If you'd like to exclude specific files from coverage, there are a couple of options:
> 
> - The first option would be to add in an exclusion filter that removes all of the files/paths that you want to exclude from your coverage data. For example, here's a [link](https://github.com/colszowka/simplecov#filters) for Defining Custom Filters instructions listed on SimpleCov's website 
> 
> - Alternatively, you could configure the project's testing framework not to generate any test coverage data for these files, which will cause them not to be mentioned in the coverage payload that is POSTed to Code Climate, at which point they won't be factored into your repository's overall coverage percentage.

**Comment by Weltraumschaf** [comment]
Since we do not use codeclimate anymore -> closed.
