### ISSUE TITLE
🚓  New Scanner: Integrate Burp Scanner

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#51]
---
name: '🚓 New Security Scanner request'
about: 'Suggest an idea for a new security scanner to integrate in this project.'
labels: 'scanner'
---

## New Scanner implementation request

**Is your feature request related to a problem? Please describe.**
As an user i want to use the [Burp Security Scanner](https://portswigger.net/burp) with the secureCodeBox, to test my WebApplications.

**Describe the solution you'd like**
Burp is integrated into the secureCodeBox

## Steps to implement a new scanner

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox-v2/tree/master/scanners)
- [ ] Add a README.md and give a brief overview of the scanner and its configuration options.
- [ ] Implement a new scanner specific scan-type.yaml
- [ ] Implement a new scanner specific parse-definition.yaml
- [ ] Add (optional) some cascading-rules.yaml
- [ ] Add (optional) a Dockerfile for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox-v2/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage

**Comment by fuhrmeistery** [comment]
I updated the Issue with our V2 Template

**Comment by Weltraumschaf** [comment]
Seems there is no need for this anymore.
