### ISSUE TITLE
value for minio persistence size.

### ISSUE THREAD

**Issue by drkgrn** [secureCodeBox/secureCodeBox#539]
My provider k8s has a persistent volume limitation:
  InvalidParameterValue: Invalid volume size: must be divisible by 8 GB.

securecodebox-operator-minio in persistent volume claims permanently in pending status. is it possible to overwrite persistence: size: 500Gi when installing via helm?

**Comment by J12934** [comment]
Hi 👋

Yup that's possible. 
Minio is included as a subchart. Every value beginning with `minio` will be passed to the minio chart, so you can configure anything supported by the minio chart. See: https://artifacthub.io/packages/helm/minio/minio

So you should be able to change this by `--set="miniopersistence.size=8Gi"` during the operator install.

**Comment by drkgrn** [comment]
@J12934 thanks a lot, --set = "minio.persistence.size = 8Gi" helped!
