### ISSUE TITLE
Change "OSI Layer" to TCP/IP Layer

### ISSUE THREAD

**Issue by JohannesZahn** [secureCodeBox/secureCodeBox#543]
### Is your feature request related to a problem?

The OSI Stack is not used in practice and therefore not applicable to the Findings generated by the SCB.

### Describe the solution you'd like

Use the TCP/IP Stack instead as described here in RFC 1122:
- Link
- Internet
- Transport
- Application

"osi_layer" should be renamed to "communication_layer"

### Describe alternatives you've considered

Instead of "tcp_ip_stack_layer" it could be called "internet_protocol_suite_layer"

**Comment by JohannesZahn** [comment]
We decided to remove the osi_layer from the findings schema and documentation for now.

**Comment by J12934** [comment]
I think this might have been closed by accident? @JohannesZahn

**Comment by JohannesZahn** [comment]
closed by secureCodeBox/secureCodeBox#543
