### ISSUE TITLE
Scan Result - Starting Scan-Processes using the REST-API

### ISSUE THREAD

**Issue by kaidippel** [secureCodeBox/secureCodeBox#57]
Hello everyone,

I want to start a Scan-Process using the REST-API, but if if do that, i don´t get results.

If I send an HTTP PUT Request, for example:

URL:
http://localhost:8080/box/processes/nmap-process

Header:
Content-Type:application/json

Body:
[
  {
    "attributes": {
      "NMAP_START_PORT": 34,
      "NMAP_IP": "localhost",
      "NMAP_END_PORT": 125
    },
    "location": "juice-shop",
    "name": "JuiceShop Test Host"
  }
]

I get the process-id as response. But where can I find the scan results?

Thank you!

**Comment by J12934** [comment]
Hi 👋
If you use the default docker-compose setup, you'll find the scan results for the scans you started in elasticsearch / kibana.  (Try checking http://localhost:5601 for kibana)

In the future you will also be able to check the results via the secureCodeBox Api.
If you want to check the status for that check out PR https://github.com/secureCodeBox/engine/pull/32. We currently plan to release this with Release 1.0 in the next couple of weeks.

**Comment by kaidippel** [comment]
Thank you! That´s exactly what i needed.
