### ISSUE TITLE
Trivy installation fails due to unknown field "name"

### ISSUE THREAD

**Issue by ammerzon** [secureCodeBox/secureCodeBox#589]
### Describe the bug

The installation of Trivy fails to an unknown field "name".

```
Release "trivy" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ScanType.spec): unknown field "name" in io.securecodebox.execution.v1.ScanType.spec
```

### Steps To Reproduce

1. Run the following command

`helm upgrade --install trivy secureCodeBox/trivy
`
### Expected behavior

The installation of the Helm chart should not fail.

### System
 - secureCodeBox: 3.0.0
 - OS: macOS
 - Kubernetes Version: v1.21.2 (client), v1.19.13-eks-8df270 (server)
 - Docker Version: 20.10.7, build f0df350

**Comment by J12934** [comment]
Hi, thanks for the report 🙏
Fix will be included in the v3.0.1 release, hopefully later today or tomorrow. 🤞
