### ISSUE TITLE
Discovery: How to Get Notification for Elastic Updates

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#598]
At the moment @J12934 has a private notification for new Elastic versions. But we need a mechanism that the whole Team will be notified for new versions, so that any of us can do the update.

@fuhrmeistery mentioned the possibility to subscribe to some feed of GitHub projects. Maybe this is a way to go.

**Comment by rseedorff** [comment]
Relates to #510 
One may try to use a bot 🤖 for that 😉
