### ISSUE TITLE
API Documentation is Outdated

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#66]
**Describe the bug**
The API methods and Objects are referencing the pre 1.0 Api.

**Steps To Reproduce**
 
- [x] https://github.com/secureCodeBox/secureCodeBox/tree/master/docs/user-guide#starting-scan-processes-using-the-rest-api
- [x] https://github.com/secureCodeBox/secureCodeBox/blob/master/docs/developer-guide/api-doc.md

**Expected behavior**
The documentation should reflect the current state of the api.

**Additional context**
Initially reported in Slack: https://securecodebox.slack.com/archives/C42NYDT46/p1551275864002700

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API Docs not correct](https://trello.com/c/C6YffoH9/231-api-docs-not-correct)

**Comment by rseedorff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate the API documentation process to prevent manual errors](https://trello.com/c/SnNcY6pw/232-automate-the-api-documentation-process-to-prevent-manual-errors)
