### ISSUE TITLE
Allow self signed certificates for s3 backend in helm chart

### ISSUE THREAD

**Issue by RixTmobilender** [secureCodeBox/secureCodeBox#676]
### Is your feature request related to a problem?

I have an existing minio installation with self-signed certs that I'd like to be able to use with securecodebox.
But there's no option to disable S3_USE_SSL when minio.enabled = false

### Describe the solution you'd like

Allow configuration of env var **S3_USE_SSL** via helm value e.g "insecure_skip_verify: true"

**Comment by J12934** [comment]
Hi 👋

You can already use the `customCACertificate.existingCertificate` to securely reference the public cert of your minio instance or the CA which signed it. See https://github.com/secureCodeBox/secureCodeBox/tree/main/operator

Would this work for you? I'd prefer to not have the option to skip tls verification build in.

**Comment by RixTmobilender** [comment]
@J12934 Thanks for the reply! Yes I believe that'd be enough for my use case.

> I'd prefer to not have the option to skip tls verification build in.

I guess some argument could be made for easing the deployment on "dev" environments but I'd understand, this being a security oriented projected and all 😅.

**Comment by J12934** [comment]
Nice, one thing i forgot to mention which might be relevant, the config map needs to be in the namespace of the operator and in every namespace where the scans are running (all under the same name). If you have many namespaces where the scans are running you can look into tools like https://github.com/mittwald/kubernetes-replicator to replicate them easily across namespaces.

**Comment by kaz-33** [comment]
and if the cypher is done by istio? Could i disable ssl_use?
I use fluxcd and i try to patch the value like this: 
    - patch:
        - op: replace
          path: /spec/template/spec/containers/0/env/8/value
          value: "false"

but i don't see any affect on the pod...any idea?

**Comment by kaz-33** [comment]
The template is not in relation with the deployment....
   env:
        - name: TELEMETRY_ENABLED
          value: 'false'
        - name: VERSION
          value: 4.4.1
        - name: S3_USE_SSL
          value: 'false'
path: /spec/template/spec/containers/0/env/2/value     >>> the correct position is 2.
Could you respect this value on the template?

**Comment by J12934** [comment]
Hi @kaz-33 

sure we can reconsider this, having istio handle the tls sounds resonable.
Can you open up a seperate issue and pull request with the change to the helm chart for it? This issue has been closed for over 2 years.

**Comment by kaz-33** [comment]
Hi @RixTmobilender, i try self-signed with this this parameters "customCACertificate.existingCertificate", the scan is created, but when the parser wants to push on the minio, i get this message "AxiosError: unable to verify the first certificat", any idea?

**Comment by Weltraumschaf** [comment]
@J12934 maybe We should add these somewhere in the docs for local development?

**Comment by kaz-33** [comment]
How to you apply "const httpsAgent = new https.Agent({ rejectUnauthorized: false });" in parse.env?

**Comment by kaz-33** [comment]
parser:
  env:
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: '0'
