### ISSUE TITLE
Nuclei Cannot Be Installed

### ISSUE THREAD

**Issue by fuhrmeistery** [secureCodeBox/secureCodeBox#699]
## 🐞 Bug report

Nuclei cannot be installed via helm.

### Describe the bug

When trying to install nuclei via helm the installation is stuck in "Pending" because the "nuclei-update-initial-template-cache" job never completes.

### Steps To Reproduce

1. Execute `helm install nuclei secureCodeBox/nuclei`
2. Wait
3. Look at `kubectl get pods,jobs`

### Expected behavior

The "nuclei-update-initial-template-cache" job should complete and the installation of nuclei therefore succeed

**Comment by J12934** [comment]
@fuhrmeistery your cluster probably doesn't support the `ReadOnlyMany` access mode of the cache volume.

If you disable the caching stuff in the helm chart it should install properly.

**Comment by fuhrmeistery** [comment]
Disabling the cache volume is currently breaking the scantype of the helm chart.
This is addressed in PR #700
