### ISSUE TITLE
🚓  New Scanner : Could you integrate VEGA Vulnerability scanner (written in Java)

### ISSUE THREAD

**Issue by Balaji047** [secureCodeBox/secureCodeBox#70]
---
name: '🚓 New Security Scanner request'
about: 'Suggest an idea for a new security scanner to integrate in this project.'
labels: 'scanner'
---

## New Scanner implementation request

**Is your feature request related to a problem? Please describe.**
As user, I would like to use VEGA with the secureCodeBox

**Describe the solution you'd like**
VEGA is integrated into the secureCodeBox

## Steps to implement a new scanner

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox/tree/master/scanners)
- [ ] Add a README.md and give a brief overview of the scanner and its configuration options.
- [ ] Implement a new scanner specific scan-type.yaml
- [ ] Implement a new scanner specific parse-definition.yaml
- [ ] Add (optional) some cascading-rules.yaml
- [ ] Add (optional) a Dockerfile for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage
~

**Comment by J12934** [comment]
Hi 👋
I don't know if anybody on the team has tried it out as we are pretty happy with the results of Zap and Arachni. So, we currently do not have plans to integrate VEGA directly. How does VEGA compare to those? Is VEGA better than Zap or Arachni in certain situations?

But we are always happy to receive suggestions for potential tools to integrate, thank you 😉

BTW You can always integrate scanners yourself if you really need them, the secureCodeBox engine is pretty extensible: https://github.com/secureCodeBox/secureCodeBox/blob/develop/docs/developer-guide/README.md

**Comment by rseedorff** [comment]
Hi @Balaji047 

thx for your suggestion. Do you mean this one?
- https://github.com/subgraph/Vega
- https://subgraph.com/vega

The last contribution to this project seems to be a little bit old somehow 🤔 Do you know if there is still an active development for this tool?
