### ISSUE TITLE
Make repository license recognizable to licensecheck

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#709]
## 📚 Documentation Issue
[Google Licensecheck](https://github.com/google/licensecheck) is apparently unable to recognize the license of the repository, probably because no LICENSE.txt exists. This causes issues with a [common viewer for Go package documentation](https://pkg.go.dev/github.com/secureCodeBox/secureCodeBox/operator/apis/execution/v1?utm_source=gopls#ScanType), which refuses to render documentation if it cannot identify the license.

### Where to find the issue
See the link above.

### Suggested change
Consider adding the license under [one of the several potential license file names checked by the Go package documentation portal](https://pkg.go.dev/license-policy), unless there is a reason not to do so?

This issue may be related to #573.

**Comment by Weltraumschaf** [comment]
@malexmave does it work now?

**Comment by Weltraumschaf** [comment]
I merged the workaround 25th October, so it should work or the workaround is not sufficient.

**Comment by Weltraumschaf** [comment]
Interesting to note: The [tool](https://github.com/google/licensecheck) they use has the licenses also in a subdir named `licenses`. So this should work.

**Comment by Weltraumschaf** [comment]
We have no idea how to fix that. Since we do not actively publish our operator on pkg.go.dev (because it is no library useful for someone else, go.dev just crawls it somehow...), we do not investigate this issue further.
