### ISSUE TITLE
Amass Docker Container does not use a non-numeric user

### ISSUE THREAD

**Issue by SebieF** [secureCodeBox/secureCodeBox#715]
Currently, we use the amass docker container published on dockerhub. Now we added securityContext values to every scanner. During this process, I encountered that it is necessary to set the value *runAsNonRoot* to false because they use a non-numeric user in their [Dockerfile](https://github.com/OWASP/Amass/blob/master/Dockerfile).

Otherwise, the following error is raised by kubernetes: Error: container has runAsNonRoot and image has non-numeric user (user), cannot verify user is non-root (pod: "scan-amass-scanner-dummy-scan, container: amass).

## Possible solutions

1. Create an issue in the OWASP amass project and ask them if it is possible to add a numerical user value (1001 is standard for SCB scanners)
2. Create our own dockerfile for the amass scanner.

**Comment by Zero3141** [comment]
Will be fixed in [PR1864](https://github.com/secureCodeBox/secureCodeBox/pull/1864), because we introduce our own scanner docker container

**Comment by J12934** [comment]
resolved
