### ISSUE TITLE
Replace CodeClimate with local linters

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#739]
At the moment, we are not quite happy with CodeClimate as the linter for this project, as it only happens in the CI process, not during development. We thus want to replace it with local linters wherever practical. This issue is intended to track the overall progress on this.

We will need linters / style checkers for:
- [ ] Javascript (parsers, hooks, tests): #740
- [ ] Go (Operator): #741
- [ ] YAML (Config files, scan definitions, ...): #742
- [ ] Misc. additional languages that are used in scanners or hooks (Python, Java come to mind)

Ideally, all of these linters ...
- would be run locally and in the IDE of choice, 
- with their configuration tracked inside the Git repository
- give feedback also within our CI Pipeline

Based on the comments we could give https://megalinter.github.io/latest/ a try.

**Comment by sanmai-NL** [comment]
https://github.com/secureCodeBox/secureCodeBox/issues/742#issuecomment-974630827
