### ISSUE TITLE
Local Linters: YAML

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#742]
We are looking for a YAML linter and style checker that can be run locally as part of our efforts to replace CodeClimate with a local solution (see #739 for the big picture view). This can also help to achieve a consistent format (see #620). Add and discuss your recommendations here.

**Comment by sanmai-NL** [comment]
I strongly advise to use https://megalinter.github.io/latest/.
In my experience, while it seems attractive to create some bespoke linting image or add them individually to some builder image, the time investment fiddling with such tools is not worth it.
Not that the linters in a generic linter image are not configurable, far from it!

**Comment by rseedorff** [comment]
Implemented with megalinter 👍🏻
