### ISSUE TITLE
Makefile-based scanner creation throws error

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#749]
## 🐞 Bug report
When using `make create-new-scanner NAME=something` to create a new scanner (as introduced in #706), I get an error.

### Describe the bug
```bash
mmaass@my-machine SecureCodeBox % make create-new-scanner NAME=openwpm
Copied template files to new directory ./scanners/openwpm
sed: 1: "./Makefile": invalid command code .
```

As far as I can tell, all files are created from the template as planned, but the `sed` command to replace `new-scanner` with the scanner name fails.

### Expected behavior
The command should run without errors and replace new-scanner with the provided name of the scanner inside the template files.

### System:
Mac OS 11.6, zsh shell.

**Comment by Weltraumschaf** [comment]
The problem is that sed on BSD Unix machines behaves slightly different than on GNU Linux machines: On BSD Unix the option `-i` requires an argument. On Gnu Linux you can simply omit it to make an inline sed. On BSD machines it must be`sed -i '' ...`.

**Comment by Weltraumschaf** [comment]
I fixed it. @SebieF maybe you want to look into it, I made some improvements to the make target.
