### ISSUE TITLE
Kibana access

### ISSUE THREAD

**Issue by wheelq** [secureCodeBox/secureCodeBox#75]
We were able to start dockerised securecodebox, but how do we get the data fed into Kibana (as seen on the screenshots)?

**Comment by J12934** [comment]
If you use the default `docker-compose`, you should have kibana started by default.
Then when you start new securityTest, (via the camunda task list or via the rest api) the results are automatically persisted into the elasticsearch instance. 

To see that data in kibana you'll need to set up an index pattern. The screenshot show dashboards, which get automatically created once the first scan results get persisted to elasticsearch.

**Comment by wheelq** [comment]
Thanks, I can see Kibana up and running, but no indexes are created. If I have to create index manually, I'd have to know the parameters, or do I have to build index, visualisations and dashboards manually?

**Comment by wheelq** [comment]
Those are the only indexes I can see:
![image](https://user-images.githubusercontent.com/1497172/55735584-84c9a300-5a19-11e9-9919-1a25f6cbe938.png)

Here are sample reports:
![image](https://user-images.githubusercontent.com/1497172/55735661-b04c8d80-5a19-11e9-9aa8-fa47c6635ceb.png)

And here are the findings in Kibana (no Medium or High reported):
![image](https://user-images.githubusercontent.com/1497172/55735742-da9e4b00-5a19-11e9-8407-875b153c3c41.png)

**Comment by J12934** [comment]
I think you need to submit the result form for the zap process to persist the findings. The persist step is after the review step.

**Comment by wheelq** [comment]
Ah, you're right. Noted and documented.

**Comment by wheelq** [comment]
> I think you need to submit the result form for the zap process to persist the findings. The persist step is after the review step.

By submit you mean press 'claim' ?
And where do the reports go once I claim it and press: Approved (Finished) ?

**Comment by J12934** [comment]
Yup, first you need to claim the review task and then submit it.

After that the results will get persisted by the configured persistence providers. (by default elasticsearch)

**Comment by rseedorff** [comment]
We will document this in our user guide more precisely and close this issue afterwards.

**Comment by fuhrmeistery** [comment]
Closed due to inactivity

**Comment by byteknacker** [comment]
I am using zap and zap advanced and I wish to display the results not in minio but in Kibana. The documentation is not clear on that. I have no idea how to connect the results to kibana. Can you please add more verbose details on this topic to the docs and also give us some examples? At least one example per scanner or one example inside the hook docs on Kibana and Elasticsearch. 

I am also not sure if I need both elasticsearch and kibana for this to work. Will the zap scan results be first stored in elasticsearch and then on kibana or just directly to kibana? I just need to know how to connect the dots here. Thank you!

**Comment by byteknacker** [comment]
> Closed due to inactivity

Btw, can you reopen this ticket as the docs are still unclear about it.
