### ISSUE TITLE
installation instructions are failing

### ISSUE THREAD

**Issue by nobletrout** [secureCodeBox/secureCodeBox#752]
## 🐞 Bug report
Following the "getting started" docs located [here](https://docs.securecodebox.io/docs/getting-started/installation/), lead to the following failure:
```
nobletrout@racoon:~$ helm repo add secureCodeBox https://charts.securecodebox.io
"secureCodeBox" has been added to your repositories
nobletrout@racoon:~$ kubectl create namespace securecodebox-system
namespace/securecodebox-system created
nobletrout@racoon:~$ helm --namespace securecodebox-system upgrade --install securecodebox-operator secureCodeBox/operator
Release "securecodebox-operator" does not exist. Installing it now.
Error: create: failed to create: Secret "sh.helm.release.v1.securecodebox-operator.v1" is invalid: data: Too long: must have at most 1048576 bytes
```

### Steps To Reproduce
Do the steps outlined above

### System (please complete the following information):

OS: Ubuntu 20.04.2 LTS
Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-3+83e2bb7ee39726", GitCommit:"83e2bb7ee3972654beca02a12a94777da22d6669", GitTreeState:"clean", BuildDate:"2021-09-28T16:03:11Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-3+83e2bb7ee39726", GitCommit:"83e2bb7ee3972654beca02a12a94777da22d6669", GitTreeState:"clean", BuildDate:"2021-09-28T15:36:44Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
k8s environment: microk8s v1.21.5

**Comment by J12934** [comment]
Hi 👋 thanks for the bug report.

There seems to be an issue in our helm chart publishing process in which we accidentally package unneeded files into the chart archive. (There is somewhat recursive nested `operator.tgz` in the [operator helm chart](https://charts.securecodebox.io/charts/operator-3.2.0.tgz). Will try to publish a bug fix release for this tomorrow.

Until then you can pin to the operator chart to `--version 3.1.1` which doesn't have this issue.
