### ISSUE TITLE
make scanner-docs / hook-docs fails on MacOS

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#754]
## 🐞 Bug report
Running `make scanner-docs` or `make hook-docs` fails on OS X.

### Describe the bug
```bash
$ make scanner-docs
# Start in the scanners folder
cd scanners
# https://github.com/koalaman/shellcheck/wiki/SC2044
find . -type f -name Chart.yaml -print0 | while IFS= read -r -d '' chart; do
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [scanner-docs] Error 2
```

```bash
$ make hook-docs
.: ⚙ Generate Helm Docs.
# Start in the hooks folder
cd hooks
# https://github.com/koalaman/shellcheck/wiki/SC2044
find . -type f -name Chart.yaml -print0 | while IFS= read -r -d '' chart; do
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [hook-docs] Error 2
```

Adding backslashes to the ends of all relevant lines of the make command results in new issues with "unexpected token: then", and fixing that results in errors where the variables aren't set correctly, so the `cd` fails etc. - it seems to be fairly fundamentally broken on OS X at the moment.

### Steps To Reproduce
Run the command on OS X :).

### System
OS X, zsh.

**Comment by Weltraumschaf** [comment]
Root cause is that `make` shipped w/ macOS does not support `.ONESHELL` which has the effect that each line is run in its own subshell. So the initial `cd` into the scanners directory does not affect the `find`.

**Comment by Weltraumschaf** [comment]
Fixed it for scanner docs. I'll fix the other targets next. There is lots of code duplication going on... I'll push separate PRs for the other targets. Some explanations are in the commit messages.

**Comment by Weltraumschaf** [comment]
Just working on some code cleanup.
