### ISSUE TITLE
Update Minio Version used in Operator Helm Chart

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#755]
## ➹ New Feature implementation request

The minio version included in the operator by default is quite old. Minio themself now only rarely update [their helm chart](https://artifacthub.io/packages/helm/minio/minio), they are now recommending to use their operator. The minio operator is not really a option for us as we can't rely on that the operator is installed.

There is an alternative helm chart provided by bitnami which looks like it still gets regular update: https://artifacthub.io/packages/helm/bitnami/minio

We could switch over to the bitnami chart, but this would likely require a major release as they use different helm values for configuration.

**Comment by cfarrend** [comment]
I noticed that on their README (updated 6 months ago) that they make reference to a "vanilla helm chart" that doesn't use the
MinIO Operator that's linked [here](https://github.com/minio/minio/tree/master/helm/minio). 

Could this be a more simple replacement that doesn't require the Bitnami chart? I haven't checked the differences between the old and new chart values file yet.

**Comment by J12934** [comment]
@cfarrend 

Ahh interessting, I was always just looking at the chart on Artifact Hub (https://artifacthub.io/packages/helm/minio/minio) which hasn't been updated in a while, but it seems that they have since migrated to a new chart registry with more regular updates 👍

Thank you for the pointer, would probably be a lot easier 👍
