### ISSUE TITLE
🚓  New Scanner: Integrate Astra (REST API) Scanner

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#76]
---
name: '🚓 New Security Scanner request'
about: 'Suggest an idea for a new security scanner to integrate in this project.'
labels: 'scanner'
---

## New Scanner implementation request

**Is your feature request related to a problem? Please describe.**
As an user i want to use test my REST APIs based on best practices with the secureCodeBox.

Therefore, the ASTRA Tool could be helpful:
- https://github.com/flipkart-incubator/Astra

**Describe the solution you'd like**
ASTRA is integrated into the secureCodeBox

## Steps to implement a new scanner

- [ ] Create a new folder with the name of the [scanner here](https://github.com/secureCodeBox/secureCodeBox-v2/tree/master/scanners)
- [ ] Add a README.md and give a brief overview of the scanner and its configuration options.
- [ ] Implement a new scanner specific scan-type.yaml
- [ ] Implement a new scanner specific parse-definition.yaml
- [ ] Add (optional) some cascading-rules.yaml
- [ ] Add (optional) a Dockerfile for the scanner if there is no existing one publicly available on dockerHub
- [ ] Use the [parser-SDK](https://github.com/secureCodeBox/secureCodeBox-v2/tree/master/parser-sdk) to implement a new findings parser (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage

**Comment by y-mehta** [comment]
@rseedorff Are you working on this feature? If not, then I would love to contribute.

**Comment by Weltraumschaf** [comment]
We do not plan to integrate this scanner at the moment. If there is more need from the community for this scanner please leave a comment here.
