### ISSUE TITLE
Enhance multi tenancy support for the secureCodeBox

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#79]
**Is your feature request related to a problem? Please describe.**
Enhance the multi tenancy support of the secureCodeBox API.

This allows Users to restrict access to ability to see and work on *securityTests*. This enables Users to scan services located in isolated networks, by restricting the access to Scans to the technical users of the scanner services inside these networks. By restricting the access to the securityTest to the isolated worker it is ensured that no other worker outside this network can "steal" this job.

**Describe the solution you'd like**
The easiest way to configure multi tenancy is to create multiple camunda tenants (secureCodeBox engine) and assign the technical users to the corresponding tenant. To control to which tenant a securityTest should belong you can set the tenant attribute on the securityTest model, when starting a process. 

> Note: You need to be a member of the tenant to start a process as part of the tenant. When the tenant attribute is set to null or is not set at all the process will be started without a tenant.

Open Todos:

- [x] Add documentation on how multi tenancy works and how to use it
- [x] Find & Document a way to prevent tenant works to lock jobs without a tenant. (This should already be possible to do, by setting up the authentication correctly)

**Comment by rseedorff** [comment]
Work in progress: https://github.com/secureCodeBox/engine/pull/79

**Comment by J12934** [comment]
Docs getting created here:
https://github.com/secureCodeBox/secureCodeBox/tree/docs/multi-tenancy

**Comment by rseedorff** [comment]
Hi @J12934 i think we should merge your documentation work here because it is helpful for everyone ;-)
https://github.com/secureCodeBox/secureCodeBox/tree/docs/multi-tenancy

**Comment by J12934** [comment]
Oh good point.
Forgot that this hasn't been merged yet.
Opened up PR #100
