### ISSUE TITLE
Scans issued via CLI not visible in GUI

### ISSUE THREAD

**Issue by wheelq** [secureCodeBox/secureCodeBox#82]
After successfull launch of scan via CLI I can see the results in `job_zap_result.json` file but I am unable to find those in GUI. Are those populated?

**Comment by rseedorff** [comment]
Hi @wheelq 
do you mean the UI of the secureCodeBox Engine (Tasklist) or the Kibana Dashboard? If you launch a security scan via CLI everything should behave the same like using the Rest API directly (or the engine UI).

As @J12934 already mention i think we have to fix some bugs in the CLI, because the latest API changes are maybe not reflected in the JSON templates.

**Comment by wheelq** [comment]
Hi @rseedorff 
> do you mean the UI of the secureCodeBox Engine (Tasklist) or the Kibana Dashboard? If you launch a security scan via CLI everything should behave the same like using the Rest API directly (or the engine UI).
Both actually. None of the scans issued via CLI are visible for review/claim in the GUI
I also got another 2 questions, not sure whether should it be posted here or as a new issue:
- How do I select format of the report when launched from the CLI. I only get JSON, how do  I select XML, HTML, CSV, PDF? 
- How can I get the reports using CLI without issuing a scan? I'd like to integrate SCB in the pipeline, launched via bash scripts.

**Comment by J12934** [comment]
We don't have other report formats other than `json`.
If you need other formats i'd recommend using defect-dojo as a persistence provider, then you use the defect dojo report mechanisms to generate them.

The cli is atm only a utility to start scans. It doesn't support getting scan results without starting a scan first.

**Comment by wheelq** [comment]
> The cli is atm only a utility to start scans. It doesn't support getting scan results without starting a scan first.
That's logical, but I was more interested in getting the results from other scans, issued via GUI or a scan from 5 days ago

**Comment by J12934** [comment]
You can do this by using the api:

```bash
wget http://{engine-url}/box/securityTests/{id} --user {username} --password {password}
```

**Comment by rseedorff** [comment]
Hi @wheelq 
you are right, the CLI can be improved in that way... I'll write a new feature request for that and close this issue afterwards.

**Comment by fuhrmeistery** [comment]
Closed due to inactivity
