### ISSUE TITLE
Init container configuration through values.yaml is ignored

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#820]
## 🐞 Bug report
When implementing init containers, I added the configuration to the values.yaml files, but didn't actually pull it into the `ScanSpec`, so at the moment, it will do nothing. I'll either have to update the `ScanSpec` for all scanners to incorporate the initContainer information, or remove it from the values.yaml because there are very few cases where it is actually a good idea to configure them here.

While doing so, I should also check if there are other things that can be configured using the values.yaml but that are not actually put into the `ScanSpec` / `ParseDefinition` afterwards.

**Comment by Weltraumschaf** [comment]
@malexmave Can you try to explain it more detailed bc we (@J12934 and me) do not understand the problem.

**Comment by malexmave** [comment]
This seems to have already been resolved, at least I can't find any traces of the bug I described here.
