### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#84]
**Is your feature request related to a problem? Please describe.**
The CLI is currently very limited to only one usecase.
It would be cool to a a more cli with more functionality, e.g. starting scans, retrieving results.

**Describe the solution you'd like**
A cli with a similar structure to modern clis like docker or kubernetes, with good help texts.

CLI should be written in a way that is cross plattform and easy to maintain and expand in the future. Go would be nice usecase for it with nice libraries to write clis, e.g:

- https://github.com/spf13/cobra
- https://github.com/urfave/cli

**Additional context**
Reworking the CLI has come up in multiple issues.
 - #82
 - #81

**Comment by fuhrmeistery** [comment]
Closed due to Version 2 of secureCodeBox
