### ISSUE TITLE
Cascading Rules are not updated on helm upgrade

### ISSUE THREAD

**Issue by EndPositive** [secureCodeBox/secureCodeBox#874]
### Describe the bug
If a scanner's cascading rules are updated, helm upgrade won't update cascading rules.

### Steps To Reproduce
Locally install nmap scanner using helm. Change a cascading rule parameter. Upgrade nmap using helm. Inspect that the cascading rule installed in your cluster has not been updated.

### Expected behavior
The cascading rule should be updated.

I have a feeling this has got to do with the fact that we're including cascading rules as files and that helm can't properly diff these.

**Comment by J12934** [comment]
Mhh can't reproduce 🤔

[![asciicast](https://asciinema.org/a/BdZXUbH3DiT10jmmlKsuiqbsO.svg)](https://asciinema.org/a/BdZXUbH3DiT10jmmlKsuiqbsO)

**Comment by EndPositive** [comment]
Hmm, it seems I can't reproduce either anymore...

I'll update this issue if I have more details.
