### ISSUE TITLE
Add aquatone for domain fly overs

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#88]
---
name: "➹ Feature request"
about: "Suggest an idea for this project"

---

**Is your feature request related to a problem? Please describe.**

- When performing subdomain or network scans the results are pretty abstract, and require some amount of further research to determine whats running on a host and get a good overview.
 
**Describe the solution you'd like**

- Provide an easy way to screenshot every http port of all found hosts and get the results displayed back in a nice overview. One nice tool for that is aquatone: (https://github.com/michenriksen/aquatone) which does exactly that.

**Describe alternatives you've considered**

- Do the same outside of the secureCodeBox.
- Open every page by hand

**Additional context**

- ~~This will be a challenging problem, as the results aka screenshots are by definition large and will in most likelihood require some sort of alternative blob storage for large files, outside the camunda engine.~~

**Comment by rseedorff** [comment]
Fixed with #206 with an alternative solution
