### ISSUE TITLE
Resource limit for each scan

### ISSUE THREAD

**Issue by l4mb0san** [secureCodeBox/secureCodeBox#907]
## Your Question

By default, I set the resource.limit to memory=256Mi and resource.request to memory=128Mi. But if some of my Container Images are larger than 1Gb, there is a crash when scanning, so I increased Trivy's default resource.limit up to 1Gb and resource.request 512Mi to complete. But this will cause k8s to be OOMkilled when I apply multiple scans at the same time, so I want to adjust the resource for each scan. How can I do that?

**Comment by J12934** [comment]
Hi 👋
Currently there is no way to adjust the resource limits and requests per scan.
This is something we are considering to add to the Scan Custom Resource thought, as this would indeed be helpful 👍

Currently the easiest way to workaround this is to separate the scans into different namespaces and creating a separate namespace for resource hungry scans where the scanType for the scanner is customized to have higher limits.

In the question you've said you have used the helm property `resource.requests` & `resource.limits`, our scan type helm charts are using `scanner.resource.requests` & `scanner.resource.limits` to indicate that these limits are only applied to the scan job not the parser / hooks. You can check if the requests / limits were applied correctly by looking at the yaml definition of the scanType resource: `kubectl get scantypes -oyaml`

**Comment by l4mb0san** [comment]
Thanks your solutions @J12934
"_separate the scans into different namespaces and creating a separate namespace for resource hungry scans_" or "_limit the number of concurrent scans_" will be 2 solutions for my current time
