### ISSUE TITLE
🚧 Makefile commands for integration tests (Consistency)

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#940]
Currently, scanner integration tests have a global command to be launched, [defined in scanners.mk](https://github.com/secureCodeBox/secureCodeBox/blob/32b9da8cdb1c71fdf293767eef7cf1cba0f04b0c/scanners.mk#L81) - but all scanners that actually use integration tests [overwrite the command in their own Makefiles](https://github.com/secureCodeBox/secureCodeBox/blob/32b9da8cdb1c71fdf293767eef7cf1cba0f04b0c/scanners/nmap/Makefile#L14). The command from the global Makefile does not work for scanners (it uses incorrect paths), so any scanner that does not overwrite it in its own Makefile will not have working integration tests (this was the case for Gitleaks until the changes introduced in #830).

Does someone know why this is the case, and if there is any reason not to just replace the global command with the ones that are used by the scanners? The structure of the global integration tests matches the layout actually used for the hooks (as in: where are the integration test definitions placed?), so is this a case of an incomplete refactoring?

**Comment by EndPositive** [comment]
See this small discussion: https://github.com/secureCodeBox/secureCodeBox/pull/712#issuecomment-938607194

**Comment by Ilyesbdlala** [comment]
This issue will be resolved through #756, #965 and #717. Our goal is to minimize allowing scanners from locally overwriting the main scanners.mk makefile. We would like also to remove the makefile dependency on relative paths and working directories. And instead use absolute paths.
