### ISSUE TITLE
SCB Bot doc generation deviates from CI doc generation

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#953]
## 🐞 Bug report
The SCB-Bot is keeping our dependencies up to date, and also runs a documentation updater as part of that process to regenerate the helm docs. It seems like the process it uses deviates from that of the CI helm-docs update, because the two seem to be fighting - the bot [changes the docs in a specific way](https://github.com/secureCodeBox/secureCodeBox/pull/952/commits/6951029770744a0cad873834842bdb18b7ca41b7) (that seems incorrect to me), the other [reverts the change](8faa2b85252abcd6d0b04469099c805344d1168d). Both commits come from https://github.com/secureCodeBox/secureCodeBox/pull/952/.

### Expected behavior
I would expect the doc generation process of the bot to match that of the CI process, so we don't have unnecessary edit wars between our different automations 😁 .

**Comment by Weltraumschaf** [comment]
Seems to be resolved.
