### ISSUE TITLE
Verify PRs for Correct SPDX Header in Main Repo

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/secureCodeBox#957]
Implement a check which verifies that PRs have the valid SPDX headers:

```
# SPDX-FileCopyrightText:  the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0
```

**Comment by Weltraumschaf** [comment]
Also for defectdojo-client.

**Comment by Weltraumschaf** [comment]
Maybe we can reuse the [reuse](https://git.fsfe.org/reuse/tool) tool for that.

**Comment by Zero3141** [comment]
See my comment in https://github.com/secureCodeBox/secureCodeBox/pull/1961#issuecomment-1720954545. We should fix all license problems before integrating it into the CI (especially when setting it to `Required`)

**Comment by Zero3141** [comment]
Some files like GitHub Actions files don't support license headers or files. We could bulk-license whole directories by adding its path to the `.reuse/dep5` file in the root directory. See [here](https://reuse.software/faq/#bulk-license) and [here](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) for more information

**Comment by Zero3141** [comment]
We have multiple images with a special license. For example, [2020-09-08-blini.jpg](https://github.com/secureCodeBox/secureCodeBox/blob/main/documentation/static/img/blog/2020-09-08-blini.jpg) in the `documentation/static/img/blog` folder, is published under the Pixabay Content License. However, this license is not known by reuse-tool. Unfortunately, it is not possible to ignore certain files (see [here](https://github.com/fsfe/reuse-tool/issues/28)).

**Comment by Weltraumschaf** [comment]
Searched for OWASP license for the Logo. TL;DR they don't give a license: https://owasp.org/www-policy/operational/mark-usage-guidelines

Tried to figure out how to set the tags in files for such edge cases: https://spdx.github.io/spdx-spec/v2.3/file-information/

**Comment by Weltraumschaf** [comment]
File exclusion is not possible by design: https://reuse.software/faq/#exclude-file
