### ISSUE TITLE
Can i create a new hook?

### ISSUE THREAD

**Issue by l4mb0san** [secureCodeBox/secureCodeBox#962]
Hi everybody,

I have some needs for storing, processing scan results (findings.json), so I want to create a hook to handle when scanning is finished, but I can't find documentation on how to create a new hook on https://docs.securecodebox.io. Securecodebox already supports this feature yet?

**Comment by J12934** [comment]
Hi 👋

Yup that's possible and documented :)
See: https://docs.securecodebox.io/docs/contributing/integrating-a-hook

**Comment by J12934** [comment]
Closing for now, feel free to reopen or ask questions in slack if the docs aren't clear 😀
