### ISSUE TITLE
Re-enable ZAP-advanced CI tests

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#963]
We currently have the ZAP Advanced scans disabled in CI because they run too long. We would like to get them working again. One proposal is:
- Run them in the CI [if files related to ZAP-Advanced have changed (but not otherwise)](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files), and
- run them in a nightly build to test them against (merged) changes to operator, SDK, etc.

Other options can also be viable and are left at the discretion of the person implementing this.

**Comment by RamiSouai** [comment]
Running the tests only in a nightly build is pretty straightforward (See #986). However, having the test conditionally trigger based on changed files isn't as simple. 

The [on:push:path](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files) directive can only apply to entire workflows, not individual jobs. The only mechanism to conditionally trigger jobs is [jobs.<job_id>.if](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) and AFAIK, there is no way to access the modified files in a commit throught [Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts)
